export type ShortcutNode = {
  id: string;
  label: string;
  path: string;
  chapter: string;
  sceneName?: string;
  x: number;
  y: number;
};

export type ShortcutEdge = {
  from: string;
  to: string;
  label?: string;
};

export const shortcutNodes: ShortcutNode[] = [
  {
    id: "prologue_start",
    label: "沙丘之夜",
    path: "prologue_start",
    chapter: "序章",
    sceneName: "沙丘之夜",
    x: 8,
    y: 52,
  },
  {
    id: "prologue_at_door",
    label: "行宫夜门",
    path: "prologue_at_door",
    chapter: "序章",
    sceneName: "沙丘行宫·夜",
    x: 26,
    y: 52,
  },
  {
    id: "prologue_side_hall",
    label: "偏殿密谈",
    path: "prologue_side_hall",
    chapter: "序章",
    sceneName: "沙丘行宫·偏殿",
    x: 44,
    y: 52,
  },
  {
    id: "prologue_choice_a",
    label: "同意矫诏",
    path: "prologue_choice_a",
    chapter: "序章",
    sceneName: "沙丘之谋·同谋",
    x: 64,
    y: 16,
  },
  {
    id: "prologue_choice_b",
    label: "拒绝告发",
    path: "prologue_choice_b",
    chapter: "序章",
    sceneName: "沙丘之谋·决绝",
    x: 64,
    y: 52,
  },
  {
    id: "prologue_choice_c",
    label: "暗中布局",
    path: "prologue_choice_c",
    chapter: "序章",
    sceneName: "沙丘之谋·隐忍",
    x: 64,
    y: 88,
  },
  {
    id: "prologue_choice_b1",
    label: "告发 IF",
    path: "prologue_choice_b1",
    chapter: "序章",
    sceneName: "沙丘之谋·告发(IF)",
    x: 86,
    y: 14,
  },
  {
    id: "prologue_choice_b1_2",
    label: "告发失败",
    path: "prologue_choice_b1_2",
    chapter: "序章",
    sceneName: "沙丘之谋·告发失败",
    x: 86,
    y: 44,
  },
  {
    id: "prologue_choice_b2",
    label: "保持沉默",
    path: "prologue_choice_b2",
    chapter: "序章",
    sceneName: "沙丘之谋·沉默",
    x: 86,
    y: 74,
  },
  {
    id: "prologue_edict_strategy",
    label: "矫诏定策",
    path: "prologue_edict_strategy",
    chapter: "序章",
    sceneName: "沙丘行宫·矫诏定策",
    x: 108,
    y: 52,
  },
  {
    id: "prologue_edict_death",
    label: "赐死扶苏",
    path: "prologue_edict_death",
    chapter: "序章",
    sceneName: "矫诏定策·赐死",
    x: 130,
    y: 30,
  },
  {
    id: "prologue_edict_exile",
    label: "流放扶苏",
    path: "prologue_edict_exile",
    chapter: "序章",
    sceneName: "矫诏定策·流放",
    x: 130,
    y: 52,
  },
  {
    id: "prologue_edict_delay",
    label: "拖延待变",
    path: "prologue_edict_delay",
    chapter: "序章",
    sceneName: "矫诏定策·拖延",
    x: 130,
    y: 88,
  },
  {
    id: "prologue_secret_room",
    label: "密室内",
    path: "prologue_secret_room",
    chapter: "序章",
    sceneName: "沙丘行宫·密室内",
    x: 152,
    y: 52,
  },
  {
    id: "prologue_departure",
    label: "沙丘启程",
    path: "prologue_departure",
    chapter: "序章",
    sceneName: "沙丘行宫·出发",
    x: 172,
    y: 52,
  },
  {
    id: "prologue_end",
    label: "序章终",
    path: "prologue_end",
    chapter: "序章",
    sceneName: "序章·终",
    x: 192,
    y: 52,
  },
  {
    id: "prologue_b1_morning",
    label: "扶苏线晨光",
    path: "prologue_b1_morning",
    chapter: "序章",
    sceneName: "沙丘行宫·晨",
    x: 108,
    y: 300,
  },
  {
    id: "prologue_if_end",
    label: "IF 线开启",
    path: "if_chapter1_start",
    chapter: "序章",
    sceneName: "序章·终·扶苏即位线",
    x: 130,
    y: 300,
  },
  {
    id: "if_chapter1_start",
    label: "IF一章前情",
    path: "if_chapter1_start",
    chapter: "IF第一章",
    sceneName: "IF线第一章·前情",
    x: 152,
    y: 300,
  },
  {
    id: "if_chapter1_enthronement",
    label: "扶苏即位",
    path: "if_chapter1_enthronement",
    chapter: "IF第一章",
    sceneName: "扶苏即位·章台殿",
    x: 174,
    y: 300,
  },
  {
    id: "if_chapter1_brothers",
    label: "兄弟对峙",
    path: "if_chapter1_brothers",
    chapter: "IF第一章",
    sceneName: "偏殿·兄弟对峙",
    x: 196,
    y: 300,
  },
  {
    id: "if_chapter1_yongcheng",
    label: "雍城闭门",
    path: "if_chapter1_yongcheng",
    chapter: "IF第一章",
    sceneName: "命运分岔·雍城闭门",
    x: 218,
    y: 282,
  },
  {
    id: "if_chapter1_bashu",
    label: "巴蜀之封",
    path: "if_chapter1_bashu",
    chapter: "IF第一章",
    sceneName: "命运分岔·巴蜀之封",
    x: 218,
    y: 318,
  },
  {
    id: "if_chapter1_zhao_prison",
    label: "赵高最后一课",
    path: "if_chapter1_zhao_prison",
    chapter: "IF第一章",
    sceneName: "廷尉狱·赵高的最后一课",
    x: 242,
    y: 300,
  },
  {
    id: "if_chapter1_zhao_shadow",
    label: "相信阴影",
    path: "if_chapter1_zhao_shadow",
    chapter: "IF第一章",
    sceneName: "赵高的最后一课·阴影",
    x: 266,
    y: 282,
  },
  {
    id: "if_chapter1_zhao_reject",
    label: "拒绝赵高",
    path: "if_chapter1_zhao_reject",
    chapter: "IF第一章",
    sceneName: "赵高的最后一课·拒绝",
    x: 266,
    y: 318,
  },
  {
    id: "if_chapter1_departure",
    label: "离京",
    path: "if_chapter1_departure",
    chapter: "IF第一章",
    sceneName: "咸阳城外·离京",
    x: 290,
    y: 300,
  },
  {
    id: "if_chapter1_ziying_road",
    label: "途中遇子婴",
    path: "if_chapter1_ziying_road",
    chapter: "IF第一章",
    sceneName: "路途·遇见子婴",
    x: 312,
    y: 300,
  },
  {
    id: "if_chapter1_reports",
    label: "新朝奏报",
    path: "if_chapter1_reports",
    chapter: "IF第一章",
    sceneName: "新朝气象·奏报选段",
    x: 334,
    y: 300,
  },
  {
    id: "if_chapter1_garden",
    label: "菜园论政",
    path: "if_chapter1_garden",
    chapter: "IF第一章",
    sceneName: "子婴辞行·菜园论政",
    x: 356,
    y: 300,
  },
  {
    id: "if_chapter1_result",
    label: "IF一章终",
    path: "if_chapter1_result",
    chapter: "IF第一章",
    sceneName: "IF线第一章·终",
    x: 378,
    y: 300,
  },
  {
    id: "if_chapter2_start",
    label: "IF二章前情",
    path: "if_chapter2_start",
    chapter: "IF第二章",
    sceneName: "IF线第二章·前情",
    x: 400,
    y: 300,
  },
  {
    id: "if_chapter2_court_debate",
    label: "分封之争",
    path: "if_chapter2_court_debate",
    chapter: "IF第二章",
    sceneName: "章台殿·分封之争",
    x: 422,
    y: 300,
  },
  {
    id: "if_chapter2_fusu_mengyi",
    label: "扶苏蒙毅",
    path: "if_chapter2_fusu_mengyi",
    chapter: "IF第二章",
    sceneName: "偏殿·扶苏与蒙毅",
    x: 444,
    y: 300,
  },
  {
    id: "if_chapter2_huhai_daily",
    label: "胡亥日常",
    path: "if_chapter2_huhai_daily",
    chapter: "IF第二章",
    sceneName: "雍城巴蜀·胡亥的日常",
    x: 466,
    y: 300,
  },
  {
    id: "if_chapter2_zhao_visitor",
    label: "神秘访客",
    path: "if_chapter2_zhao_visitor",
    chapter: "IF第二章",
    sceneName: "廷尉狱·神秘访客",
    x: 488,
    y: 300,
  },
  {
    id: "if_chapter2_secret_letter",
    label: "匿名密信",
    path: "if_chapter2_secret_letter",
    chapter: "IF第二章",
    sceneName: "雍城巴蜀·密信",
    x: 510,
    y: 300,
  },
  {
    id: "if_chapter2_send_letter",
    label: "呈送扶苏",
    path: "if_chapter2_send_letter",
    chapter: "IF第二章",
    sceneName: "密信抉择·呈送扶苏",
    x: 534,
    y: 270,
  },
  {
    id: "if_chapter2_keep_letter",
    label: "留存密信",
    path: "if_chapter2_keep_letter",
    chapter: "IF第二章",
    sceneName: "密信抉择·留存密信",
    x: 534,
    y: 300,
  },
  {
    id: "if_chapter2_burn_letter",
    label: "焚毁密信",
    path: "if_chapter2_burn_letter",
    chapter: "IF第二章",
    sceneName: "密信抉择·焚毁密信",
    x: 534,
    y: 330,
  },
  {
    id: "if_chapter2_court_followup",
    label: "争议激化",
    path: "if_chapter2_court_followup",
    chapter: "IF第二章",
    sceneName: "咸阳朝堂·分封之争续",
    x: 558,
    y: 300,
  },
  {
    id: "if_chapter2_fusu_night",
    label: "扶苏独白",
    path: "if_chapter2_fusu_night",
    chapter: "IF第二章",
    sceneName: "寝殿·扶苏独白",
    x: 580,
    y: 300,
  },
  {
    id: "if_chapter2_ziying_warning",
    label: "子婴告诫",
    path: "if_chapter2_ziying_warning",
    chapter: "IF第二章",
    sceneName: "雍城巴蜀·子婴告诫",
    x: 602,
    y: 300,
  },
  {
    id: "if_chapter2_zhao_game",
    label: "赵高棋局",
    path: "if_chapter2_zhao_game",
    chapter: "IF第二章",
    sceneName: "廷尉狱·赵高的棋局",
    x: 624,
    y: 300,
  },
  {
    id: "if_chapter2_result",
    label: "IF二章终",
    path: "if_chapter2_result",
    chapter: "IF第二章",
    sceneName: "IF线第二章·终",
    x: 646,
    y: 300,
  },
  {
    id: "if_chapter3_start",
    label: "IF三章前情",
    path: "if_chapter3_start",
    chapter: "IF第三章",
    sceneName: "IF线第三章·前情",
    x: 670,
    y: 300,
  },
  {
    id: "if_chapter3_fief_edict",
    label: "蜀王之封",
    path: "if_chapter3_fief_edict",
    chapter: "IF第三章",
    sceneName: "雍城巴蜀·封王诏书",
    x: 694,
    y: 300,
  },
  {
    id: "if_chapter3_li_meng_talk",
    label: "李蒙夜谈",
    path: "if_chapter3_li_meng_talk",
    chapter: "IF第三章",
    sceneName: "咸阳·李斯府",
    x: 718,
    y: 300,
  },
  {
    id: "if_chapter3_shu_court",
    label: "蜀王府",
    path: "if_chapter3_shu_court",
    chapter: "IF第三章",
    sceneName: "成都·蜀王府",
    x: 742,
    y: 300,
  },
  {
    id: "if_chapter3_road_choice",
    label: "蜀王道路",
    path: "if_chapter3_road_choice",
    chapter: "IF第三章",
    sceneName: "蜀王的道路",
    x: 766,
    y: 300,
  },
  {
    id: "if_chapter3_lay_low",
    label: "韬光养晦",
    path: "if_chapter3_lay_low",
    chapter: "IF第三章",
    sceneName: "蜀王道路·韬光养晦",
    x: 790,
    y: 258,
  },
  {
    id: "if_chapter3_train_army",
    label: "整军经武",
    path: "if_chapter3_train_army",
    chapter: "IF第三章",
    sceneName: "蜀王道路·整军经武",
    x: 790,
    y: 300,
  },
  {
    id: "if_chapter3_contact_kings",
    label: "联络诸王",
    path: "if_chapter3_contact_kings",
    chapter: "IF第三章",
    sceneName: "蜀王道路·联络诸王",
    x: 790,
    y: 342,
  },
  {
    id: "if_chapter3_qi_letter",
    label: "齐王密信",
    path: "if_chapter3_qi_letter",
    chapter: "IF第三章",
    sceneName: "齐地·公子高的密信",
    x: 816,
    y: 300,
  },
  {
    id: "if_chapter3_zhao_trace",
    label: "赵高踪迹",
    path: "if_chapter3_zhao_trace",
    chapter: "IF第三章",
    sceneName: "关东·赵高踪迹",
    x: 840,
    y: 300,
  },
  {
    id: "if_chapter3_ziying_advice",
    label: "子婴进言",
    path: "if_chapter3_ziying_advice",
    chapter: "IF第三章",
    sceneName: "成都·子婴进言",
    x: 864,
    y: 300,
  },
  {
    id: "if_chapter3_fusu_worry",
    label: "扶苏查奏",
    path: "if_chapter3_fusu_worry",
    chapter: "IF第三章",
    sceneName: "咸阳宫·扶苏的忧虑",
    x: 888,
    y: 300,
  },
  {
    id: "if_chapter3_zhao_game",
    label: "关东棋局",
    path: "if_chapter3_zhao_game",
    chapter: "IF第三章",
    sceneName: "关东·赵高棋局",
    x: 912,
    y: 300,
  },
  {
    id: "if_chapter3_second_letter",
    label: "密信再现",
    path: "if_chapter3_second_letter",
    chapter: "IF第三章",
    sceneName: "成都·密信再现",
    x: 936,
    y: 300,
  },
  {
    id: "if_chapter3_send_again",
    label: "再次呈送",
    path: "if_chapter3_send_again",
    chapter: "IF第三章",
    sceneName: "密信再现·再次呈送",
    x: 960,
    y: 258,
  },
  {
    id: "if_chapter3_wait",
    label: "静观其变",
    path: "if_chapter3_wait",
    chapter: "IF第三章",
    sceneName: "密信再现·静观其变",
    x: 960,
    y: 300,
  },
  {
    id: "if_chapter3_reconcile_qi",
    label: "主动化解",
    path: "if_chapter3_reconcile_qi",
    chapter: "IF第三章",
    sceneName: "密信再现·主动化解",
    x: 960,
    y: 342,
  },
  {
    id: "if_chapter3_result",
    label: "IF三章终",
    path: "if_chapter3_result",
    chapter: "IF第三章",
    sceneName: "IF线第三章·终",
    x: 986,
    y: 300,
  },
  {
    id: "if_chapter4_start",
    label: "IF四章前情",
    path: "if_chapter4_start",
    chapter: "IF第四章",
    sceneName: "IF线第四章·前情",
    x: 1012,
    y: 300,
  },
  {
    id: "if_chapter4_summons",
    label: "入朝诏书",
    path: "if_chapter4_summons",
    chapter: "IF第四章",
    sceneName: "成都·入朝诏书",
    x: 1038,
    y: 300,
  },
  {
    id: "if_chapter4_guest_house",
    label: "朝会前夜",
    path: "if_chapter4_guest_house",
    chapter: "IF第四章",
    sceneName: "咸阳客馆·朝会前夜",
    x: 1064,
    y: 300,
  },
  {
    id: "if_chapter4_court_first",
    label: "宗室朝会",
    path: "if_chapter4_court_first",
    chapter: "IF第四章",
    sceneName: "章台殿·宗室大朝会",
    x: 1090,
    y: 300,
  },
  {
    id: "if_chapter4_support_kings",
    label: "朝堂直谏",
    path: "if_chapter4_support_kings",
    chapter: "IF第四章",
    sceneName: "朝堂对答·朝堂直谏",
    x: 1118,
    y: 250,
  },
  {
    id: "if_chapter4_neutral",
    label: "朝堂中立",
    path: "if_chapter4_neutral",
    chapter: "IF第四章",
    sceneName: "朝堂对答·朝堂中立",
    x: 1118,
    y: 300,
  },
  {
    id: "if_chapter4_support_fusu",
    label: "朝堂驳斥",
    path: "if_chapter4_support_fusu",
    chapter: "IF第四章",
    sceneName: "朝堂对答·朝堂驳斥",
    x: 1118,
    y: 350,
  },
  {
    id: "if_chapter4_brother_drink",
    label: "兄弟夜话",
    path: "if_chapter4_brother_drink",
    chapter: "IF第四章",
    sceneName: "偏殿·兄弟夜话",
    x: 1148,
    y: 300,
  },
  {
    id: "if_chapter4_advise_power",
    label: "劝放权",
    path: "if_chapter4_advise_power",
    chapter: "IF第四章",
    sceneName: "兄弟夜话·劝放权",
    x: 1176,
    y: 250,
  },
  {
    id: "if_chapter4_tui_en",
    label: "推恩之策",
    path: "if_chapter4_tui_en",
    chapter: "IF第四章",
    sceneName: "兄弟夜话·推恩之策",
    x: 1176,
    y: 300,
  },
  {
    id: "if_chapter4_silence",
    label: "沉默以对",
    path: "if_chapter4_silence",
    chapter: "IF第四章",
    sceneName: "兄弟夜话·沉默以对",
    x: 1176,
    y: 350,
  },
  {
    id: "if_chapter4_zhao_report",
    label: "赵高未死",
    path: "if_chapter4_zhao_report",
    chapter: "IF第四章",
    sceneName: "咸阳客馆·子婴密报",
    x: 1206,
    y: 300,
  },
  {
    id: "if_chapter4_report_zhao",
    label: "密报扶苏",
    path: "if_chapter4_report_zhao",
    chapter: "IF第四章",
    sceneName: "赵高踪迹·密报扶苏",
    x: 1234,
    y: 275,
  },
  {
    id: "if_chapter4_hold_zhao",
    label: "继续观察",
    path: "if_chapter4_hold_zhao",
    chapter: "IF第四章",
    sceneName: "赵高踪迹·继续观察",
    x: 1234,
    y: 325,
  },
  {
    id: "if_chapter4_qi_visit",
    label: "齐王夜访",
    path: "if_chapter4_qi_visit",
    chapter: "IF第四章",
    sceneName: "咸阳客馆·齐王夜访",
    x: 1262,
    y: 300,
  },
  {
    id: "if_chapter4_zhao_closes",
    label: "赵高收网",
    path: "if_chapter4_zhao_closes",
    chapter: "IF第四章",
    sceneName: "关东·赵高收网",
    x: 1290,
    y: 300,
  },
  {
    id: "if_chapter4_third_letter",
    label: "第三封信",
    path: "if_chapter4_third_letter",
    chapter: "IF第四章",
    sceneName: "咸阳客馆·第三封密信",
    x: 1318,
    y: 300,
  },
  {
    id: "if_chapter4_return_shu",
    label: "返蜀证清白",
    path: "if_chapter4_return_shu",
    chapter: "IF第四章",
    sceneName: "何去何从·返蜀证清白",
    x: 1348,
    y: 240,
  },
  {
    id: "if_chapter4_stay_xianyang",
    label: "滞留咸阳",
    path: "if_chapter4_stay_xianyang",
    chapter: "IF第四章",
    sceneName: "何去何从·滞留咸阳",
    x: 1348,
    y: 300,
  },
  {
    id: "if_chapter4_secret_departure",
    label: "秘密离京",
    path: "if_chapter4_secret_departure",
    chapter: "IF第四章",
    sceneName: "何去何从·秘密离京",
    x: 1348,
    y: 360,
  },
  {
    id: "if_chapter4_hunt_zhao",
    label: "追杀赵高",
    path: "if_chapter4_hunt_zhao",
    chapter: "IF第四章",
    sceneName: "秘密离京·追杀赵高",
    x: 1378,
    y: 340,
  },
  {
    id: "if_chapter4_leave_zhao",
    label: "赵高在逃",
    path: "if_chapter4_leave_zhao",
    chapter: "IF第四章",
    sceneName: "秘密离京·赵高在逃",
    x: 1378,
    y: 380,
  },
  {
    id: "if_chapter4_final_court",
    label: "最后朝会",
    path: "if_chapter4_final_court",
    chapter: "IF第四章",
    sceneName: "章台殿·朝会最后一日",
    x: 1410,
    y: 300,
  },
  {
    id: "if_chapter4_result",
    label: "IF四章终",
    path: "if_chapter4_result",
    chapter: "IF第四章",
    sceneName: "IF线第四章·终",
    x: 1440,
    y: 300,
  },
  {
    id: "if_chapter5_start",
    label: "IF五章前情",
    path: "if_chapter5_start",
    chapter: "IF第五章",
    sceneName: "IF线第五章·前情",
    x: 1470,
    y: 300,
  },
  {
    id: "if_chapter5_qi_rebellion",
    label: "齐王起兵",
    path: "if_chapter5_qi_rebellion",
    chapter: "IF第五章",
    sceneName: "齐地·临淄·烽火起",
    x: 1500,
    y: 300,
  },
  {
    id: "if_chapter5_fusu_decision",
    label: "扶苏平叛",
    path: "if_chapter5_fusu_decision",
    chapter: "IF第五章",
    sceneName: "咸阳·扶苏的抉择",
    x: 1530,
    y: 300,
  },
  {
    id: "if_chapter5_zhao_game",
    label: "赵高火种",
    path: "if_chapter5_zhao_game",
    chapter: "IF第五章",
    sceneName: "关东·赵高棋局",
    x: 1560,
    y: 300,
  },
  {
    id: "if_chapter5_zhao_status",
    label: "赵高判定",
    path: "if_chapter5_zhao_status",
    chapter: "IF第五章",
    sceneName: "赵高状态判定",
    x: 1590,
    y: 300,
  },
  {
    id: "if_chapter5_shu_choice",
    label: "蜀王抉择",
    path: "if_chapter5_shu_choice",
    chapter: "IF第五章",
    sceneName: "巴蜀·蜀王的抉择",
    x: 1620,
    y: 300,
  },
  {
    id: "if_chapter5_loyal_suppression",
    label: "表忠助剿",
    path: "if_chapter5_loyal_suppression",
    chapter: "IF第五章",
    sceneName: "蜀王抉择·表忠助剿",
    x: 1650,
    y: 230,
  },
  {
    id: "if_chapter5_wait_and_see",
    label: "按兵不动",
    path: "if_chapter5_wait_and_see",
    chapter: "IF第五章",
    sceneName: "蜀王抉择·按兵不动",
    x: 1650,
    y: 300,
  },
  {
    id: "if_chapter5_contact_qi",
    label: "暗通齐王",
    path: "if_chapter5_contact_qi",
    chapter: "IF第五章",
    sceneName: "蜀王抉择·暗通齐王",
    x: 1650,
    y: 370,
  },
  {
    id: "if_chapter5_xianyang_winter",
    label: "咸阳冬雪",
    path: "if_chapter5_xianyang_winter",
    chapter: "IF第五章",
    sceneName: "咸阳客馆·冬雪",
    x: 1620,
    y: 390,
  },
  {
    id: "if_chapter5_bashu_military",
    label: "巴蜀整军",
    path: "if_chapter5_bashu_military",
    chapter: "IF第五章",
    sceneName: "巴蜀·整军备战",
    x: 1620,
    y: 450,
  },
  {
    id: "if_chapter5_raise_army",
    label: "巴蜀起兵",
    path: "if_chapter5_raise_army",
    chapter: "IF第五章",
    sceneName: "巴蜀·起兵",
    x: 1650,
    y: 450,
  },
  {
    id: "if_chapter5_common_war",
    label: "函谷关战",
    path: "if_chapter5_common_war",
    chapter: "IF第五章",
    sceneName: "函谷关外·章邯与齐王",
    x: 1680,
    y: 230,
  },
  {
    id: "if_chapter5_fusu_and_qi",
    label: "兄弟问罪",
    path: "if_chapter5_fusu_and_qi",
    chapter: "IF第五章",
    sceneName: "咸阳·扶苏与公子高",
    x: 1710,
    y: 230,
  },
  {
    id: "if_chapter5_fusu_awake",
    label: "扶苏觉醒",
    path: "if_chapter5_fusu_awake",
    chapter: "IF第五章",
    sceneName: "咸阳·扶苏的觉醒",
    x: 1740,
    y: 230,
  },
  {
    id: "if_chapter5_renjun_assistant_ending",
    label: "仁君之佐",
    path: "if_chapter5_renjun_assistant_ending",
    chapter: "IF第五章",
    sceneName: "结局·仁君之佐",
    x: 1780,
    y: 160,
  },
  {
    id: "if_chapter5_bashu_king_ending",
    label: "巴蜀王",
    path: "if_chapter5_bashu_king_ending",
    chapter: "IF第五章",
    sceneName: "结局·巴蜀王",
    x: 1780,
    y: 220,
  },
  {
    id: "if_chapter5_shu_choice_ending",
    label: "蜀王选择",
    path: "if_chapter5_shu_choice_ending",
    chapter: "IF第五章",
    sceneName: "结局·蜀王的选择",
    x: 1780,
    y: 280,
  },
  {
    id: "if_chapter5_xianyang_winter_ending",
    label: "咸阳冬天",
    path: "if_chapter5_xianyang_winter_ending",
    chapter: "IF第五章",
    sceneName: "结局·咸阳的冬天",
    x: 1780,
    y: 340,
  },
  {
    id: "if_chapter5_kings_alliance_ending",
    label: "诸王同盟",
    path: "if_chapter5_kings_alliance_ending",
    chapter: "IF第五章",
    sceneName: "结局·诸王同盟",
    x: 1780,
    y: 400,
  },
  {
    id: "if_chapter5_brothers_war_ending",
    label: "兄弟阋墙",
    path: "if_chapter5_brothers_war_ending",
    chapter: "IF第五章",
    sceneName: "结局·兄弟阋墙",
    x: 1780,
    y: 460,
  },
  {
    id: "if_chapter5_fusu_death_ending",
    label: "扶苏之殂",
    path: "if_chapter5_fusu_death_ending",
    chapter: "IF第五章",
    sceneName: "隐藏结局·扶苏之殂",
    x: 1780,
    y: 520,
  },
  {
    id: "if_chapter5_epilogue",
    label: "IF全剧终",
    path: "if_chapter5_epilogue",
    chapter: "IF第五章",
    sceneName: "终章·尾声",
    x: 1820,
    y: 340,
  },
  {
    id: "chapter1_start",
    label: "咸阳灵堂",
    path: "chapter1_start",
    chapter: "第一章",
    sceneName: "咸阳宫·灵堂",
    x: 214,
    y: 52,
  },
  {
    id: "chapter1_side_hall",
    label: "即位偏殿",
    path: "chapter1_side_hall",
    chapter: "第一章",
    sceneName: "咸阳宫·偏殿",
    x: 234,
    y: 52,
  },
  {
    id: "chapter1_fusu_dead",
    label: "扶苏已死",
    path: "chapter1_fusu_dead",
    chapter: "第一章",
    sceneName: "扶苏已死",
    x: 254,
    y: 24,
  },
  {
    id: "chapter1_fusu_exiled",
    label: "扶苏流放",
    path: "chapter1_fusu_exiled",
    chapter: "第一章",
    sceneName: "扶苏流放",
    x: 254,
    y: 52,
  },
  {
    id: "chapter1_fusu_delayed",
    label: "扶苏返京",
    path: "chapter1_fusu_delayed",
    chapter: "第一章",
    sceneName: "扶苏返京",
    x: 254,
    y: 80,
  },
  {
    id: "chapter1_fusu_common_end",
    label: "蒙氏阴影",
    path: "chapter1_fusu_common_end",
    chapter: "第一章",
    sceneName: "蒙氏阴影",
    x: 276,
    y: 52,
  },
  {
    id: "meng_decision",
    label: "章台廷议",
    path: "meng_decision",
    chapter: "第一章",
    sceneName: "咸阳宫·章台殿",
    x: 298,
    y: 52,
  },
  {
    id: "chapter1_meng_execute",
    label: "处死蒙氏",
    path: "chapter1_meng_execute",
    chapter: "第一章",
    sceneName: "蒙氏处死",
    x: 320,
    y: 24,
  },
  {
    id: "chapter1_meng_retain",
    label: "赦免留用",
    path: "chapter1_meng_retain",
    chapter: "第一章",
    sceneName: "蒙氏留用",
    x: 320,
    y: 52,
  },
  {
    id: "chapter1_meng_dismiss",
    label: "贬为庶民",
    path: "chapter1_meng_dismiss",
    chapter: "第一章",
    sceneName: "蒙氏免官",
    x: 320,
    y: 80,
  },
  {
    id: "chapter1_night_study",
    label: "寝殿奏章",
    path: "chapter1_night_study",
    chapter: "第一章",
    sceneName: "咸阳宫·寝殿",
    x: 342,
    y: 52,
  },
  {
    id: "chapter1_secret_record",
    label: "秘密记录",
    path: "chapter1_secret_record",
    chapter: "第一章",
    sceneName: "隐藏场景·秘密记录",
    x: 364,
    y: 28,
  },
  {
    id: "chapter1_clan_list",
    label: "宗室名单",
    path: "chapter1_clan_list",
    chapter: "第一章",
    sceneName: "咸阳宫·偏殿",
    x: 364,
    y: 72,
  },
  {
    id: "chapter1_ziying_meet",
    label: "子婴密会",
    path: "chapter1_ziying_meet",
    chapter: "第一章",
    sceneName: "隐藏场景·子婴密会",
    x: 386,
    y: 56,
  },
  {
    id: "chapter1_result",
    label: "第一章终",
    path: "chapter1_result",
    chapter: "第一章",
    sceneName: "第一章·终",
    x: 408,
    y: 82,
  },
  {
    id: "chapter2_start",
    label: "前情回顾",
    path: "chapter2_start",
    chapter: "第二章",
    sceneName: "第二章·前情",
    x: 430,
    y: 52,
  },
  {
    id: "chapter2_bedchamber",
    label: "宗室名单",
    path: "chapter2_bedchamber",
    chapter: "第二章",
    sceneName: "咸阳宫·寝殿",
    x: 452,
    y: 52,
  },
  {
    id: "chapter2_clan_debate",
    label: "偏殿廷议",
    path: "chapter2_clan_debate",
    chapter: "第二章",
    sceneName: "咸阳宫·偏殿",
    x: 474,
    y: 52,
  },
  {
    id: "chapter2_clan_massacre",
    label: "大开杀戒",
    path: "chapter2_clan_massacre",
    chapter: "第二章",
    sceneName: "宗室屠戮·大开杀戒",
    x: 498,
    y: 20,
  },
  {
    id: "chapter2_clan_limited",
    label: "只杀威胁者",
    path: "chapter2_clan_limited",
    chapter: "第二章",
    sceneName: "宗室屠戮·只杀威胁者",
    x: 498,
    y: 52,
  },
  {
    id: "chapter2_clan_protect",
    label: "庇护宗室",
    path: "chapter2_clan_protect",
    chapter: "第二章",
    sceneName: "宗室屠戮·庇护宗室",
    x: 498,
    y: 84,
  },
  {
    id: "chapter2_assassin",
    label: "刺客夜",
    path: "chapter2_assassin",
    chapter: "第二章",
    sceneName: "咸阳宫·刺客夜",
    x: 522,
    y: 52,
  },
  {
    id: "chapter2_guard_spies",
    label: "禁卫眼线",
    path: "chapter2_guard_spies",
    chapter: "第二章",
    sceneName: "隐藏场景·禁卫眼线",
    x: 544,
    y: 26,
  },
  {
    id: "chapter2_projects",
    label: "土木廷议",
    path: "chapter2_projects",
    chapter: "第二章",
    sceneName: "咸阳宫·章台殿",
    x: 566,
    y: 52,
  },
  {
    id: "chapter2_project_continue",
    label: "继续工程",
    path: "chapter2_project_continue",
    chapter: "第二章",
    sceneName: "大兴土木·继续工程",
    x: 590,
    y: 20,
  },
  {
    id: "chapter2_project_relief",
    label: "暂缓休养",
    path: "chapter2_project_relief",
    chapter: "第二章",
    sceneName: "大兴土木·暂缓休养",
    x: 590,
    y: 52,
  },
  {
    id: "chapter2_project_tax",
    label: "改革税制",
    path: "chapter2_project_tax",
    chapter: "第二章",
    sceneName: "大兴土木·改革税制",
    x: 590,
    y: 84,
  },
  {
    id: "chapter2_ziying_garden",
    label: "子婴菜园",
    path: "chapter2_ziying_garden",
    chapter: "第二章",
    sceneName: "公子婴的菜园",
    x: 614,
    y: 52,
  },
  {
    id: "chapter2_secret_room",
    label: "密室续录",
    path: "chapter2_secret_room",
    chapter: "第二章",
    sceneName: "咸阳宫·密室",
    x: 638,
    y: 28,
  },
  {
    id: "chapter2_result",
    label: "第二章终",
    path: "chapter2_result",
    chapter: "第二章",
    sceneName: "第二章·终",
    x: 660,
    y: 52,
  },
  {
    id: "chapter3_start",
    label: "前情回顾",
    path: "chapter3_start",
    chapter: "第三章",
    sceneName: "第三章·前情",
    x: 682,
    y: 52,
  },
  {
    id: "chapter3_dazexiang",
    label: "大泽乡",
    path: "chapter3_dazexiang",
    chapter: "第三章",
    sceneName: "大泽乡",
    x: 704,
    y: 52,
  },
  {
    id: "chapter3_rebellion_report",
    label: "起义军报",
    path: "chapter3_rebellion_report",
    chapter: "第三章",
    sceneName: "咸阳宫·章台殿·起义军报",
    x: 726,
    y: 52,
  },
  {
    id: "chapter3_suppress",
    label: "全力镇压",
    path: "chapter3_suppress",
    chapter: "第三章",
    sceneName: "应对起义·全力镇压",
    x: 750,
    y: 20,
  },
  {
    id: "chapter3_appease",
    label: "安抚招安",
    path: "chapter3_appease",
    chapter: "第三章",
    sceneName: "应对起义·安抚招安",
    x: 750,
    y: 52,
  },
  {
    id: "chapter3_ignore",
    label: "置之不理",
    path: "chapter3_ignore",
    chapter: "第三章",
    sceneName: "应对起义·坐视叛乱",
    x: 750,
    y: 84,
  },
  {
    id: "chapter3_li_si_conflict",
    label: "李赵决裂",
    path: "chapter3_li_si_conflict",
    chapter: "第三章",
    sceneName: "咸阳宫·偏殿·李赵决裂",
    x: 774,
    y: 52,
  },
  {
    id: "chapter3_execute_li_si",
    label: "诛杀李斯",
    path: "chapter3_execute_li_si",
    chapter: "第三章",
    sceneName: "李斯之死·处死李斯",
    x: 798,
    y: 20,
  },
  {
    id: "chapter3_protect_li_si",
    label: "保李斯",
    path: "chapter3_protect_li_si",
    chapter: "第三章",
    sceneName: "李斯之死·保李斯",
    x: 798,
    y: 52,
  },
  {
    id: "chapter3_kill_zhao_gao",
    label: "反杀赵高",
    path: "chapter3_kill_zhao_gao",
    chapter: "第三章",
    sceneName: "李斯之死·反杀赵高",
    x: 798,
    y: 84,
  },
  {
    id: "chapter3_zhang_han_report_alive",
    label: "章邯战报",
    path: "chapter3_zhang_han_report_alive",
    chapter: "第三章",
    sceneName: "章邯的战报·赵高存活",
    x: 824,
    y: 36,
  },
  {
    id: "chapter3_zhang_han_report_dead",
    label: "章邯战报",
    path: "chapter3_zhang_han_report_dead",
    chapter: "第三章",
    sceneName: "章邯的战报·赵高已死",
    x: 824,
    y: 112,
  },
  {
    id: "chapter3_reinforce_alive",
    label: "求援决策",
    path: "chapter3_reinforce_alive",
    chapter: "第三章",
    sceneName: "章邯求援·赵高存活",
    x: 850,
    y: 36,
  },
  {
    id: "chapter3_reinforce_dead",
    label: "求援决策",
    path: "chapter3_reinforce_dead",
    chapter: "第三章",
    sceneName: "章邯求援·赵高已死",
    x: 850,
    y: 112,
  },
  {
    id: "chapter3_support_zhang_alive",
    label: "全力增援",
    path: "chapter3_support_zhang_alive",
    chapter: "第三章",
    sceneName: "章邯求援·全力增援",
    x: 876,
    y: 12,
  },
  {
    id: "chapter3_suspect_zhang_alive",
    label: "拒绝增援",
    path: "chapter3_suspect_zhang_alive",
    chapter: "第三章",
    sceneName: "章邯求援·拒绝增援",
    x: 876,
    y: 42,
  },
  {
    id: "chapter3_send_zhao_front",
    label: "调虎离山",
    path: "chapter3_send_zhao_front",
    chapter: "第三章",
    sceneName: "章邯求援·调虎离山",
    x: 876,
    y: 72,
  },
  {
    id: "chapter3_support_zhang_dead",
    label: "全力增援",
    path: "chapter3_support_zhang_dead",
    chapter: "第三章",
    sceneName: "章邯求援·全力增援·赵高已死",
    x: 876,
    y: 100,
  },
  {
    id: "chapter3_suspect_zhang_dead",
    label: "拒绝增援",
    path: "chapter3_suspect_zhang_dead",
    chapter: "第三章",
    sceneName: "章邯求援·拒绝增援·赵高已死",
    x: 876,
    y: 130,
  },
  {
    id: "chapter3_eat_zhao_party",
    label: "蚕食赵党",
    path: "chapter3_eat_zhao_party",
    chapter: "第三章",
    sceneName: "隐藏场景·蚕食赵党",
    x: 902,
    y: 72,
  },
  {
    id: "chapter3_ziying_garden_alive",
    label: "菜园论政",
    path: "chapter3_ziying_garden_alive",
    chapter: "第三章",
    sceneName: "公子婴菜园·赵高存活",
    x: 928,
    y: 48,
  },
  {
    id: "chapter3_ziying_garden_dead",
    label: "菜园论政",
    path: "chapter3_ziying_garden_dead",
    chapter: "第三章",
    sceneName: "公子婴菜园·赵高已死",
    x: 928,
    y: 116,
  },
  {
    id: "chapter3_result_alive",
    label: "第三章终",
    path: "chapter3_result_alive",
    chapter: "第三章",
    sceneName: "第三章·终·赵高存活",
    x: 954,
    y: 48,
  },
  {
    id: "chapter3_result_dead",
    label: "第三章终",
    path: "chapter3_result_dead",
    chapter: "第三章",
    sceneName: "第三章·终·赵高已死",
    x: 954,
    y: 116,
  },
  {
    id: "chapter4_start",
    label: "前情回顾",
    path: "chapter4_start",
    chapter: "第四章",
    sceneName: "第四章·前情",
    x: 982,
    y: 82,
  },
  {
    id: "chapter4_deer_court",
    label: "指鹿为马",
    path: "chapter4_deer_court",
    chapter: "第四章",
    sceneName: "咸阳宫·章台殿·指鹿为马",
    x: 1008,
    y: 36,
  },
  {
    id: "chapter4_deer_is_deer",
    label: "指鹿为鹿",
    path: "chapter4_deer_is_deer",
    chapter: "第四章",
    sceneName: "指鹿为马·指鹿为鹿",
    x: 1034,
    y: 12,
  },
  {
    id: "chapter4_deer_is_horse",
    label: "违心称马",
    path: "chapter4_deer_is_horse",
    chapter: "第四章",
    sceneName: "指鹿为马·违心称马",
    x: 1034,
    y: 36,
  },
  {
    id: "chapter4_countermove",
    label: "反将一军",
    path: "chapter4_countermove",
    chapter: "第四章",
    sceneName: "指鹿为马·反将一军",
    x: 1034,
    y: 60,
  },
  {
    id: "chapter4_breakout_plan",
    label: "破局三策",
    path: "chapter4_breakout_plan",
    chapter: "第四章",
    sceneName: "咸阳宫·寝殿·破局三策",
    x: 1062,
    y: 36,
  },
  {
    id: "chapter4_call_zhang_han",
    label: "密诏章邯",
    path: "chapter4_call_zhang_han",
    chapter: "第四章",
    sceneName: "破局三策·密诏章邯",
    x: 1090,
    y: 12,
  },
  {
    id: "chapter4_leave_xianyang",
    label: "离京出巡",
    path: "chapter4_leave_xianyang",
    chapter: "第四章",
    sceneName: "破局三策·离京出巡",
    x: 1090,
    y: 36,
  },
  {
    id: "chapter4_palace_assassination",
    label: "宫中刺杀",
    path: "chapter4_palace_assassination",
    chapter: "第四章",
    sceneName: "破局三策·宫中刺杀",
    x: 1090,
    y: 60,
  },
  {
    id: "chapter4_julu_report_alive",
    label: "巨鹿战报",
    path: "chapter4_julu_report_alive",
    chapter: "第四章",
    sceneName: "巨鹿战报·赵高存活",
    x: 1118,
    y: 36,
  },
  {
    id: "chapter4_regency_court",
    label: "亲政朝会",
    path: "chapter4_regency_court",
    chapter: "第四章",
    sceneName: "亲政之路·章台殿",
    x: 1118,
    y: 106,
  },
  {
    id: "chapter4_li_si_policy",
    label: "李斯削藩",
    path: "chapter4_li_si_policy",
    chapter: "第四章",
    sceneName: "亲政之路·李斯削藩策",
    x: 1146,
    y: 106,
  },
  {
    id: "chapter4_reform_garden",
    label: "改法之议",
    path: "chapter4_reform_garden",
    chapter: "第四章",
    sceneName: "亲政之路·改法之议",
    x: 1174,
    y: 106,
  },
  {
    id: "chapter4_centralize",
    label: "削藩集权",
    path: "chapter4_centralize",
    chapter: "第四章",
    sceneName: "治国之路·削藩集权",
    x: 1202,
    y: 86,
  },
  {
    id: "chapter4_tui_en",
    label: "推恩分封",
    path: "chapter4_tui_en",
    chapter: "第四章",
    sceneName: "治国之路·推恩分封",
    x: 1202,
    y: 110,
  },
  {
    id: "chapter4_reform_law",
    label: "改秦法",
    path: "chapter4_reform_law",
    chapter: "第四章",
    sceneName: "治国之路·改秦法",
    x: 1202,
    y: 134,
  },
  {
    id: "chapter4_julu_report_dead",
    label: "巨鹿求援",
    path: "chapter4_julu_report_dead",
    chapter: "第四章",
    sceneName: "巨鹿之援·赵高已死",
    x: 1230,
    y: 110,
  },
  {
    id: "chapter4_personal_campaign",
    label: "亲征",
    path: "chapter4_personal_campaign",
    chapter: "第四章",
    sceneName: "巨鹿之援·亲征",
    x: 1258,
    y: 70,
  },
  {
    id: "chapter4_send_zhao_supervise",
    label: "赵高监军",
    path: "chapter4_send_zhao_supervise",
    chapter: "第四章",
    sceneName: "巨鹿之援·赵高监军",
    x: 1146,
    y: 94,
  },
  {
    id: "chapter4_reinforce_only",
    label: "增援不亲征",
    path: "chapter4_reinforce_only",
    chapter: "第四章",
    sceneName: "巨鹿之援·增援不亲征",
    x: 1258,
    y: 118,
  },
  {
    id: "chapter4_abandon_zhang",
    label: "坐视章邯",
    path: "chapter4_abandon_zhang",
    chapter: "第四章",
    sceneName: "巨鹿之援·坐视章邯",
    x: 1258,
    y: 142,
  },
  {
    id: "chapter4_result",
    label: "第四章终",
    path: "chapter4_result",
    chapter: "第四章",
    sceneName: "第四章·终",
    x: 1286,
    y: 106,
  },
  {
    id: "chapter5_start",
    label: "第五章前情",
    path: "chapter5_start",
    chapter: "第五章",
    sceneName: "第五章·前情",
    x: 1314,
    y: 106,
  },
  {
    id: "chapter5_mingjun_camp",
    label: "函谷军帐",
    path: "chapter5_mingjun_camp",
    chapter: "第五章",
    sceneName: "函谷关外·大军营帐",
    x: 1342,
    y: 48,
  },
  {
    id: "chapter5_julu_encircle",
    label: "围而不战",
    path: "chapter5_julu_encircle",
    chapter: "第五章",
    sceneName: "巨鹿决战·围而不战",
    x: 1370,
    y: 24,
  },
  {
    id: "chapter5_julu_charge",
    label: "主动出击",
    path: "chapter5_julu_charge",
    chapter: "第五章",
    sceneName: "巨鹿决战·主动出击",
    x: 1370,
    y: 72,
  },
  {
    id: "chapter5_mingjun_ending_choice",
    label: "明君结局分支",
    path: "chapter5_mingjun_ending_choice",
    chapter: "第五章",
    sceneName: "明君线·结局分支",
    x: 1398,
    y: 48,
  },
  {
    id: "chapter5_ending_mingjun",
    label: "明君逆袭",
    path: "chapter5_ending_mingjun",
    chapter: "第五章",
    sceneName: "结局·明君逆袭",
    x: 1426,
    y: 4,
  },
  {
    id: "chapter5_ending_rebuild",
    label: "重塑天下",
    path: "chapter5_ending_rebuild",
    chapter: "第五章",
    sceneName: "结局·重塑天下",
    x: 1426,
    y: 30,
  },
  {
    id: "chapter5_ending_hidden_dragon",
    label: "隐龙出渊",
    path: "chapter5_ending_hidden_dragon",
    chapter: "第五章",
    sceneName: "结局·隐龙出渊",
    x: 1426,
    y: 56,
  },
  {
    id: "chapter5_ending_redemption",
    label: "英雄救赎",
    path: "chapter5_ending_redemption",
    chapter: "第五章",
    sceneName: "结局·英雄救赎",
    x: 1426,
    y: 82,
  },
  {
    id: "chapter5_ending_zhang_surrender",
    label: "章邯之降",
    path: "chapter5_ending_zhang_surrender",
    chapter: "第五章",
    sceneName: "结局·章邯之降",
    x: 1426,
    y: 108,
  },
  {
    id: "chapter5_puppet_court",
    label: "清洗赵党",
    path: "chapter5_puppet_court",
    chapter: "第五章",
    sceneName: "咸阳宫·章台殿·清洗赵党",
    x: 1342,
    y: 126,
  },
  {
    id: "chapter5_purge_hard",
    label: "雷霆清洗",
    path: "chapter5_purge_hard",
    chapter: "第五章",
    sceneName: "清洗赵党·雷霆手段",
    x: 1370,
    y: 116,
  },
  {
    id: "chapter5_purge_soft",
    label: "分化瓦解",
    path: "chapter5_purge_soft",
    chapter: "第五章",
    sceneName: "清洗赵党·分化瓦解",
    x: 1370,
    y: 144,
  },
  {
    id: "chapter5_puppet_ending_choice",
    label: "翻身结局分支",
    path: "chapter5_puppet_ending_choice",
    chapter: "第五章",
    sceneName: "傀儡翻身线·结局分支",
    x: 1398,
    y: 130,
  },
  {
    id: "chapter5_ending_puppet",
    label: "傀儡翻身",
    path: "chapter5_ending_puppet",
    chapter: "第五章",
    sceneName: "结局·傀儡翻身",
    x: 1426,
    y: 132,
  },
  {
    id: "chapter5_ending_borrow_blade",
    label: "借刀杀人",
    path: "chapter5_ending_borrow_blade",
    chapter: "第五章",
    sceneName: "结局·借刀杀人",
    x: 1426,
    y: 158,
  },
  {
    id: "chapter5_fall_wangyi",
    label: "望夷终局",
    path: "chapter5_fall_wangyi",
    chapter: "第五章",
    sceneName: "望夷宫·雪夜",
    x: 1342,
    y: 170,
  },
  {
    id: "chapter5_ending_true_second",
    label: "真实二世",
    path: "chapter5_ending_true_second",
    chapter: "第五章",
    sceneName: "结局·真实的二世",
    x: 1370,
    y: 166,
  },
  {
    id: "chapter5_ending_betrayed",
    label: "众叛亲离",
    path: "chapter5_ending_betrayed",
    chapter: "第五章",
    sceneName: "结局·众叛亲离",
    x: 1398,
    y: 180,
  },
  {
    id: "chapter5_ending_ziying_inherit",
    label: "子婴继承",
    path: "chapter5_ending_ziying_inherit",
    chapter: "第五章",
    sceneName: "结局·子婴的继承",
    x: 1426,
    y: 178,
  },
  {
    id: "chapter5_ending_clan_butcher",
    label: "宗室屠夫终局",
    path: "chapter5_ending_clan_butcher",
    chapter: "第五章",
    sceneName: "结局·宗室屠夫",
    x: 1426,
    y: 200,
  },
  {
    id: "chapter5_exile_snow",
    label: "逃亡雪地",
    path: "chapter5_exile_snow",
    chapter: "第五章",
    sceneName: "咸阳郊外·雪地",
    x: 1342,
    y: 208,
  },
  {
    id: "chapter5_ending_bashu",
    label: "巴蜀之主",
    path: "chapter5_ending_bashu",
    chapter: "第五章",
    sceneName: "结局·巴蜀之主",
    x: 1370,
    y: 208,
  },
  {
    id: "chapter5_ending_north_wolf",
    label: "北方之狼",
    path: "chapter5_ending_north_wolf",
    chapter: "第五章",
    sceneName: "结局·北方之狼",
    x: 1398,
    y: 208,
  },
  {
    id: "chapter5_ending_east_sea",
    label: "东渡沧海",
    path: "chapter5_ending_east_sea",
    chapter: "第五章",
    sceneName: "结局·东渡沧海",
    x: 1426,
    y: 220,
  },
  {
    id: "chapter5_ending_rise_again",
    label: "东山再起",
    path: "chapter5_ending_rise_again",
    chapter: "第五章",
    sceneName: "结局·东山再起",
    x: 1426,
    y: 244,
  },
  {
    id: "chapter5_brother_cell",
    label: "兄弟相残",
    path: "chapter5_brother_cell",
    chapter: "第五章",
    sceneName: "扶苏线·章台囚室",
    x: 1342,
    y: 300,
  },
  {
    id: "chapter5_final_comment",
    label: "终章史评",
    path: "chapter5_final_comment",
    chapter: "第五章",
    sceneName: "终章·史家评语",
    x: 1480,
    y: 106,
  },
];

export const shortcutEdges: ShortcutEdge[] = [
  { from: "prologue_start", to: "prologue_at_door" },
  { from: "prologue_at_door", to: "prologue_side_hall" },
  { from: "prologue_side_hall", to: "prologue_choice_a", label: "A" },
  { from: "prologue_side_hall", to: "prologue_choice_b", label: "B" },
  { from: "prologue_side_hall", to: "prologue_choice_c", label: "C" },
  { from: "prologue_choice_b", to: "prologue_choice_b1", label: "B1" },
  { from: "prologue_choice_b", to: "prologue_choice_b1_2", label: "B1-2" },
  { from: "prologue_choice_b", to: "prologue_choice_b2", label: "B2" },
  { from: "prologue_choice_a", to: "prologue_edict_strategy" },
  { from: "prologue_choice_b1", to: "prologue_b1_morning" },
  { from: "prologue_choice_b1_2", to: "prologue_edict_strategy" },
  { from: "prologue_choice_b2", to: "prologue_edict_strategy" },
  { from: "prologue_choice_c", to: "prologue_edict_strategy" },
  { from: "prologue_edict_strategy", to: "prologue_edict_death", label: "一" },
  { from: "prologue_edict_strategy", to: "prologue_edict_exile", label: "二" },
  { from: "prologue_edict_strategy", to: "prologue_edict_delay", label: "三" },
  { from: "prologue_edict_death", to: "prologue_secret_room" },
  { from: "prologue_edict_exile", to: "prologue_secret_room" },
  { from: "prologue_edict_delay", to: "prologue_secret_room" },
  { from: "prologue_secret_room", to: "prologue_departure" },
  { from: "prologue_departure", to: "prologue_end" },
  { from: "prologue_b1_morning", to: "prologue_if_end" },
  { from: "prologue_if_end", to: "if_chapter1_start" },
  { from: "if_chapter1_start", to: "if_chapter1_enthronement" },
  { from: "if_chapter1_enthronement", to: "if_chapter1_brothers" },
  { from: "if_chapter1_brothers", to: "if_chapter1_yongcheng", label: "A" },
  { from: "if_chapter1_brothers", to: "if_chapter1_bashu", label: "B" },
  { from: "if_chapter1_yongcheng", to: "if_chapter1_zhao_prison" },
  { from: "if_chapter1_bashu", to: "if_chapter1_zhao_prison" },
  { from: "if_chapter1_zhao_prison", to: "if_chapter1_zhao_shadow", label: "A" },
  { from: "if_chapter1_zhao_prison", to: "if_chapter1_zhao_reject", label: "B" },
  { from: "if_chapter1_zhao_shadow", to: "if_chapter1_departure" },
  { from: "if_chapter1_zhao_reject", to: "if_chapter1_departure" },
  { from: "if_chapter1_departure", to: "if_chapter1_ziying_road" },
  { from: "if_chapter1_ziying_road", to: "if_chapter1_reports" },
  { from: "if_chapter1_reports", to: "if_chapter1_garden" },
  { from: "if_chapter1_garden", to: "if_chapter1_result" },
  { from: "if_chapter1_result", to: "if_chapter2_start" },
  { from: "if_chapter2_start", to: "if_chapter2_court_debate" },
  { from: "if_chapter2_court_debate", to: "if_chapter2_fusu_mengyi" },
  { from: "if_chapter2_fusu_mengyi", to: "if_chapter2_huhai_daily" },
  { from: "if_chapter2_huhai_daily", to: "if_chapter2_zhao_visitor" },
  { from: "if_chapter2_zhao_visitor", to: "if_chapter2_secret_letter" },
  { from: "if_chapter2_secret_letter", to: "if_chapter2_send_letter", label: "A" },
  { from: "if_chapter2_secret_letter", to: "if_chapter2_keep_letter", label: "B" },
  { from: "if_chapter2_secret_letter", to: "if_chapter2_burn_letter", label: "C" },
  { from: "if_chapter2_send_letter", to: "if_chapter2_court_followup" },
  { from: "if_chapter2_keep_letter", to: "if_chapter2_court_followup" },
  { from: "if_chapter2_burn_letter", to: "if_chapter2_court_followup" },
  { from: "if_chapter2_court_followup", to: "if_chapter2_fusu_night" },
  { from: "if_chapter2_fusu_night", to: "if_chapter2_ziying_warning" },
  { from: "if_chapter2_ziying_warning", to: "if_chapter2_zhao_game" },
  { from: "if_chapter2_zhao_game", to: "if_chapter2_result" },
  { from: "if_chapter2_result", to: "if_chapter3_start" },
  { from: "if_chapter3_start", to: "if_chapter3_fief_edict" },
  { from: "if_chapter3_fief_edict", to: "if_chapter3_li_meng_talk" },
  { from: "if_chapter3_li_meng_talk", to: "if_chapter3_shu_court" },
  { from: "if_chapter3_shu_court", to: "if_chapter3_road_choice" },
  { from: "if_chapter3_road_choice", to: "if_chapter3_lay_low", label: "A" },
  { from: "if_chapter3_road_choice", to: "if_chapter3_train_army", label: "B" },
  { from: "if_chapter3_road_choice", to: "if_chapter3_contact_kings", label: "C" },
  { from: "if_chapter3_lay_low", to: "if_chapter3_qi_letter" },
  { from: "if_chapter3_train_army", to: "if_chapter3_qi_letter" },
  { from: "if_chapter3_contact_kings", to: "if_chapter3_qi_letter" },
  { from: "if_chapter3_qi_letter", to: "if_chapter3_zhao_trace" },
  { from: "if_chapter3_zhao_trace", to: "if_chapter3_ziying_advice" },
  { from: "if_chapter3_ziying_advice", to: "if_chapter3_fusu_worry" },
  { from: "if_chapter3_fusu_worry", to: "if_chapter3_zhao_game" },
  { from: "if_chapter3_zhao_game", to: "if_chapter3_second_letter" },
  { from: "if_chapter3_second_letter", to: "if_chapter3_send_again", label: "A" },
  { from: "if_chapter3_second_letter", to: "if_chapter3_wait", label: "B" },
  { from: "if_chapter3_second_letter", to: "if_chapter3_reconcile_qi", label: "C" },
  { from: "if_chapter3_send_again", to: "if_chapter3_result" },
  { from: "if_chapter3_wait", to: "if_chapter3_result" },
  { from: "if_chapter3_reconcile_qi", to: "if_chapter3_result" },
  { from: "if_chapter3_result", to: "if_chapter4_start" },
  { from: "if_chapter4_start", to: "if_chapter4_summons" },
  { from: "if_chapter4_summons", to: "if_chapter4_guest_house" },
  { from: "if_chapter4_guest_house", to: "if_chapter4_court_first" },
  { from: "if_chapter4_court_first", to: "if_chapter4_support_kings", label: "A" },
  { from: "if_chapter4_court_first", to: "if_chapter4_neutral", label: "B" },
  { from: "if_chapter4_court_first", to: "if_chapter4_support_fusu", label: "C" },
  { from: "if_chapter4_support_kings", to: "if_chapter4_brother_drink" },
  { from: "if_chapter4_neutral", to: "if_chapter4_brother_drink" },
  { from: "if_chapter4_support_fusu", to: "if_chapter4_brother_drink" },
  { from: "if_chapter4_brother_drink", to: "if_chapter4_advise_power", label: "A" },
  { from: "if_chapter4_brother_drink", to: "if_chapter4_tui_en", label: "B" },
  { from: "if_chapter4_brother_drink", to: "if_chapter4_silence", label: "C" },
  { from: "if_chapter4_advise_power", to: "if_chapter4_zhao_report" },
  { from: "if_chapter4_tui_en", to: "if_chapter4_zhao_report" },
  { from: "if_chapter4_silence", to: "if_chapter4_zhao_report" },
  { from: "if_chapter4_zhao_report", to: "if_chapter4_report_zhao", label: "报" },
  { from: "if_chapter4_zhao_report", to: "if_chapter4_hold_zhao", label: "观" },
  { from: "if_chapter4_report_zhao", to: "if_chapter4_qi_visit" },
  { from: "if_chapter4_hold_zhao", to: "if_chapter4_qi_visit" },
  { from: "if_chapter4_qi_visit", to: "if_chapter4_zhao_closes" },
  { from: "if_chapter4_zhao_closes", to: "if_chapter4_third_letter" },
  { from: "if_chapter4_third_letter", to: "if_chapter4_return_shu", label: "A" },
  { from: "if_chapter4_third_letter", to: "if_chapter4_stay_xianyang", label: "B" },
  { from: "if_chapter4_third_letter", to: "if_chapter4_secret_departure", label: "C" },
  { from: "if_chapter4_return_shu", to: "if_chapter4_final_court" },
  { from: "if_chapter4_stay_xianyang", to: "if_chapter4_final_court" },
  { from: "if_chapter4_secret_departure", to: "if_chapter4_hunt_zhao", label: "杀" },
  { from: "if_chapter4_secret_departure", to: "if_chapter4_leave_zhao", label: "留" },
  { from: "if_chapter4_hunt_zhao", to: "if_chapter4_final_court" },
  { from: "if_chapter4_leave_zhao", to: "if_chapter4_final_court" },
  { from: "if_chapter4_final_court", to: "if_chapter4_result" },
  { from: "if_chapter4_result", to: "if_chapter5_start" },
  { from: "if_chapter5_start", to: "if_chapter5_qi_rebellion" },
  { from: "if_chapter5_qi_rebellion", to: "if_chapter5_fusu_decision" },
  { from: "if_chapter5_fusu_decision", to: "if_chapter5_zhao_game" },
  { from: "if_chapter5_zhao_game", to: "if_chapter5_zhao_status" },
  { from: "if_chapter5_zhao_status", to: "if_chapter5_shu_choice", label: "返蜀" },
  { from: "if_chapter5_zhao_status", to: "if_chapter5_xianyang_winter", label: "留咸" },
  { from: "if_chapter5_zhao_status", to: "if_chapter5_bashu_military", label: "离京" },
  { from: "if_chapter5_shu_choice", to: "if_chapter5_loyal_suppression", label: "A" },
  { from: "if_chapter5_shu_choice", to: "if_chapter5_wait_and_see", label: "B" },
  { from: "if_chapter5_shu_choice", to: "if_chapter5_contact_qi", label: "C" },
  { from: "if_chapter5_loyal_suppression", to: "if_chapter5_common_war" },
  { from: "if_chapter5_common_war", to: "if_chapter5_fusu_and_qi" },
  { from: "if_chapter5_fusu_and_qi", to: "if_chapter5_fusu_awake" },
  { from: "if_chapter5_fusu_awake", to: "if_chapter5_renjun_assistant_ending" },
  { from: "if_chapter5_fusu_awake", to: "if_chapter5_shu_choice_ending" },
  { from: "if_chapter5_fusu_awake", to: "if_chapter5_fusu_death_ending", label: "隐" },
  { from: "if_chapter5_wait_and_see", to: "if_chapter5_shu_choice_ending", label: "扶" },
  { from: "if_chapter5_wait_and_see", to: "if_chapter5_xianyang_winter_ending", label: "骑" },
  { from: "if_chapter5_contact_qi", to: "if_chapter5_kings_alliance_ending" },
  { from: "if_chapter5_xianyang_winter", to: "if_chapter5_xianyang_winter_ending" },
  { from: "if_chapter5_bashu_military", to: "if_chapter5_raise_army", label: "起" },
  { from: "if_chapter5_bashu_military", to: "if_chapter5_shu_choice_ending", label: "守" },
  { from: "if_chapter5_raise_army", to: "if_chapter5_bashu_king_ending", label: "成" },
  { from: "if_chapter5_raise_army", to: "if_chapter5_brothers_war_ending", label: "败" },
  { from: "if_chapter5_renjun_assistant_ending", to: "if_chapter5_epilogue" },
  { from: "if_chapter5_bashu_king_ending", to: "if_chapter5_epilogue" },
  { from: "if_chapter5_shu_choice_ending", to: "if_chapter5_epilogue" },
  { from: "if_chapter5_xianyang_winter_ending", to: "if_chapter5_epilogue" },
  { from: "if_chapter5_kings_alliance_ending", to: "if_chapter5_epilogue" },
  { from: "if_chapter5_brothers_war_ending", to: "if_chapter5_epilogue" },
  { from: "if_chapter5_fusu_death_ending", to: "if_chapter5_epilogue" },
  { from: "prologue_end", to: "chapter1_start" },
  { from: "chapter1_start", to: "chapter1_side_hall" },
  { from: "chapter1_side_hall", to: "chapter1_fusu_dead", label: "死" },
  { from: "chapter1_side_hall", to: "chapter1_fusu_exiled", label: "流" },
  { from: "chapter1_side_hall", to: "chapter1_fusu_delayed", label: "返" },
  { from: "chapter1_fusu_dead", to: "chapter1_fusu_common_end" },
  { from: "chapter1_fusu_exiled", to: "chapter1_fusu_common_end" },
  { from: "chapter1_fusu_delayed", to: "chapter1_fusu_common_end" },
  { from: "chapter1_fusu_common_end", to: "meng_decision" },
  { from: "meng_decision", to: "chapter1_meng_execute", label: "A" },
  { from: "meng_decision", to: "chapter1_meng_retain", label: "B" },
  { from: "meng_decision", to: "chapter1_meng_dismiss", label: "C" },
  { from: "chapter1_meng_execute", to: "chapter1_night_study" },
  { from: "chapter1_meng_retain", to: "chapter1_night_study" },
  { from: "chapter1_meng_dismiss", to: "chapter1_night_study" },
  { from: "chapter1_night_study", to: "chapter1_secret_record", label: "隐" },
  { from: "chapter1_night_study", to: "chapter1_clan_list" },
  { from: "chapter1_secret_record", to: "chapter1_clan_list" },
  { from: "chapter1_clan_list", to: "chapter1_ziying_meet", label: "隐" },
  { from: "chapter1_clan_list", to: "chapter1_result", label: "主" },
  { from: "chapter1_ziying_meet", to: "chapter1_result" },
  { from: "chapter1_result", to: "chapter2_start" },
  { from: "chapter2_start", to: "chapter2_bedchamber" },
  { from: "chapter2_bedchamber", to: "chapter2_clan_debate" },
  { from: "chapter2_clan_debate", to: "chapter2_clan_massacre", label: "A" },
  { from: "chapter2_clan_debate", to: "chapter2_clan_limited", label: "B" },
  { from: "chapter2_clan_debate", to: "chapter2_clan_protect", label: "C" },
  { from: "chapter2_clan_massacre", to: "chapter2_assassin" },
  { from: "chapter2_clan_limited", to: "chapter2_assassin" },
  { from: "chapter2_clan_protect", to: "chapter2_assassin" },
  { from: "chapter2_assassin", to: "chapter2_guard_spies", label: "隐" },
  { from: "chapter2_assassin", to: "chapter2_projects", label: "主" },
  { from: "chapter2_guard_spies", to: "chapter2_projects" },
  { from: "chapter2_projects", to: "chapter2_project_continue", label: "A" },
  { from: "chapter2_projects", to: "chapter2_project_relief", label: "B" },
  { from: "chapter2_projects", to: "chapter2_project_tax", label: "C" },
  { from: "chapter2_project_continue", to: "chapter2_ziying_garden" },
  { from: "chapter2_project_relief", to: "chapter2_ziying_garden" },
  { from: "chapter2_project_tax", to: "chapter2_ziying_garden" },
  { from: "chapter2_ziying_garden", to: "chapter2_secret_room", label: "隐" },
  { from: "chapter2_ziying_garden", to: "chapter2_result", label: "主" },
  { from: "chapter2_secret_room", to: "chapter2_result" },
  { from: "chapter2_result", to: "chapter3_start" },
  { from: "chapter3_start", to: "chapter3_dazexiang" },
  { from: "chapter3_dazexiang", to: "chapter3_rebellion_report" },
  { from: "chapter3_rebellion_report", to: "chapter3_suppress", label: "A" },
  { from: "chapter3_rebellion_report", to: "chapter3_appease", label: "B" },
  { from: "chapter3_rebellion_report", to: "chapter3_ignore", label: "C" },
  { from: "chapter3_suppress", to: "chapter3_li_si_conflict" },
  { from: "chapter3_appease", to: "chapter3_li_si_conflict" },
  { from: "chapter3_ignore", to: "chapter3_li_si_conflict" },
  { from: "chapter3_li_si_conflict", to: "chapter3_execute_li_si", label: "A" },
  { from: "chapter3_li_si_conflict", to: "chapter3_protect_li_si", label: "B" },
  { from: "chapter3_li_si_conflict", to: "chapter3_kill_zhao_gao", label: "隐" },
  { from: "chapter3_execute_li_si", to: "chapter3_zhang_han_report_alive" },
  { from: "chapter3_protect_li_si", to: "chapter3_zhang_han_report_alive" },
  { from: "chapter3_kill_zhao_gao", to: "chapter3_zhang_han_report_dead" },
  { from: "chapter3_zhang_han_report_alive", to: "chapter3_reinforce_alive" },
  { from: "chapter3_zhang_han_report_dead", to: "chapter3_reinforce_dead" },
  { from: "chapter3_reinforce_alive", to: "chapter3_support_zhang_alive", label: "A" },
  { from: "chapter3_reinforce_alive", to: "chapter3_suspect_zhang_alive", label: "B" },
  { from: "chapter3_reinforce_alive", to: "chapter3_send_zhao_front", label: "C" },
  { from: "chapter3_reinforce_dead", to: "chapter3_support_zhang_dead", label: "A" },
  { from: "chapter3_reinforce_dead", to: "chapter3_suspect_zhang_dead", label: "B" },
  { from: "chapter3_support_zhang_alive", to: "chapter3_ziying_garden_alive" },
  { from: "chapter3_suspect_zhang_alive", to: "chapter3_ziying_garden_alive" },
  { from: "chapter3_send_zhao_front", to: "chapter3_eat_zhao_party", label: "隐" },
  { from: "chapter3_send_zhao_front", to: "chapter3_ziying_garden_alive", label: "主" },
  { from: "chapter3_eat_zhao_party", to: "chapter3_ziying_garden_alive" },
  { from: "chapter3_ziying_garden_alive", to: "chapter3_result_alive" },
  { from: "chapter3_support_zhang_dead", to: "chapter3_ziying_garden_dead" },
  { from: "chapter3_suspect_zhang_dead", to: "chapter3_ziying_garden_dead" },
  { from: "chapter3_ziying_garden_dead", to: "chapter3_result_dead" },
  { from: "chapter3_result_alive", to: "chapter4_start" },
  { from: "chapter3_result_dead", to: "chapter4_start" },
  { from: "chapter4_start", to: "chapter4_deer_court", label: "赵存" },
  { from: "chapter4_start", to: "chapter4_regency_court", label: "赵亡" },
  { from: "chapter4_deer_court", to: "chapter4_deer_is_deer", label: "A" },
  { from: "chapter4_deer_court", to: "chapter4_deer_is_horse", label: "B" },
  { from: "chapter4_deer_court", to: "chapter4_countermove", label: "隐" },
  { from: "chapter4_deer_is_deer", to: "chapter4_breakout_plan" },
  { from: "chapter4_deer_is_horse", to: "chapter4_breakout_plan" },
  { from: "chapter4_countermove", to: "chapter4_breakout_plan" },
  { from: "chapter4_breakout_plan", to: "chapter4_call_zhang_han", label: "A" },
  { from: "chapter4_breakout_plan", to: "chapter4_leave_xianyang", label: "B" },
  { from: "chapter4_breakout_plan", to: "chapter4_palace_assassination", label: "C" },
  { from: "chapter4_call_zhang_han", to: "chapter4_julu_report_alive" },
  { from: "chapter4_leave_xianyang", to: "chapter4_julu_report_alive" },
  { from: "chapter4_palace_assassination", to: "chapter4_regency_court" },
  { from: "chapter4_julu_report_alive", to: "chapter4_personal_campaign", label: "A" },
  { from: "chapter4_julu_report_alive", to: "chapter4_send_zhao_supervise", label: "B" },
  { from: "chapter4_julu_report_alive", to: "chapter4_abandon_zhang", label: "C" },
  { from: "chapter4_regency_court", to: "chapter4_li_si_policy" },
  { from: "chapter4_li_si_policy", to: "chapter4_reform_garden" },
  { from: "chapter4_reform_garden", to: "chapter4_centralize", label: "A" },
  { from: "chapter4_reform_garden", to: "chapter4_tui_en", label: "B" },
  { from: "chapter4_reform_garden", to: "chapter4_reform_law", label: "C" },
  { from: "chapter4_centralize", to: "chapter4_julu_report_dead" },
  { from: "chapter4_tui_en", to: "chapter4_julu_report_dead" },
  { from: "chapter4_reform_law", to: "chapter4_julu_report_dead" },
  { from: "chapter4_julu_report_dead", to: "chapter4_personal_campaign", label: "A" },
  { from: "chapter4_julu_report_dead", to: "chapter4_reinforce_only", label: "B" },
  { from: "chapter4_julu_report_dead", to: "chapter4_abandon_zhang", label: "C" },
  { from: "chapter4_personal_campaign", to: "chapter4_result" },
  { from: "chapter4_send_zhao_supervise", to: "chapter4_result" },
  { from: "chapter4_reinforce_only", to: "chapter4_result" },
  { from: "chapter4_abandon_zhang", to: "chapter4_result" },
  { from: "chapter4_result", to: "chapter5_start" },
  { from: "chapter5_start", to: "chapter5_mingjun_camp", label: "亲/赵亡" },
  { from: "chapter5_start", to: "chapter5_puppet_court", label: "赵监" },
  { from: "chapter5_start", to: "chapter5_fall_wangyi", label: "败" },
  { from: "chapter5_start", to: "chapter5_exile_snow", label: "逃" },
  { from: "chapter5_start", to: "chapter5_brother_cell", label: "IF" },
  { from: "chapter5_mingjun_camp", to: "chapter5_julu_encircle", label: "A" },
  { from: "chapter5_mingjun_camp", to: "chapter5_julu_charge", label: "B" },
  { from: "chapter5_julu_encircle", to: "chapter5_mingjun_ending_choice" },
  { from: "chapter5_julu_charge", to: "chapter5_mingjun_ending_choice" },
  { from: "chapter5_mingjun_ending_choice", to: "chapter5_ending_mingjun" },
  { from: "chapter5_mingjun_ending_choice", to: "chapter5_ending_rebuild" },
  { from: "chapter5_mingjun_ending_choice", to: "chapter5_ending_hidden_dragon", label: "隐" },
  { from: "chapter5_mingjun_ending_choice", to: "chapter5_ending_redemption", label: "救" },
  { from: "chapter5_mingjun_ending_choice", to: "chapter5_ending_zhang_surrender" },
  { from: "chapter5_puppet_court", to: "chapter5_purge_hard", label: "A" },
  { from: "chapter5_puppet_court", to: "chapter5_purge_soft", label: "B" },
  { from: "chapter5_purge_hard", to: "chapter5_puppet_ending_choice" },
  { from: "chapter5_purge_soft", to: "chapter5_puppet_ending_choice" },
  { from: "chapter5_puppet_ending_choice", to: "chapter5_ending_puppet" },
  { from: "chapter5_puppet_ending_choice", to: "chapter5_ending_borrow_blade", label: "隐" },
  { from: "chapter5_fall_wangyi", to: "chapter5_ending_true_second", label: "A" },
  { from: "chapter5_fall_wangyi", to: "chapter5_ending_betrayed", label: "B" },
  { from: "chapter5_fall_wangyi", to: "chapter5_ending_ziying_inherit", label: "C" },
  { from: "chapter5_fall_wangyi", to: "chapter5_ending_clan_butcher", label: "宗" },
  { from: "chapter5_exile_snow", to: "chapter5_ending_bashu", label: "A" },
  { from: "chapter5_exile_snow", to: "chapter5_ending_north_wolf", label: "B" },
  { from: "chapter5_exile_snow", to: "chapter5_ending_east_sea", label: "C" },
  { from: "chapter5_exile_snow", to: "chapter5_ending_rise_again", label: "隐" },
  { from: "chapter5_brother_cell", to: "chapter5_final_comment" },
  { from: "chapter5_ending_mingjun", to: "chapter5_final_comment" },
  { from: "chapter5_ending_rebuild", to: "chapter5_final_comment" },
  { from: "chapter5_ending_hidden_dragon", to: "chapter5_final_comment" },
  { from: "chapter5_ending_redemption", to: "chapter5_final_comment" },
  { from: "chapter5_ending_zhang_surrender", to: "chapter5_final_comment" },
  { from: "chapter5_ending_puppet", to: "chapter5_final_comment" },
  { from: "chapter5_ending_borrow_blade", to: "chapter5_final_comment" },
  { from: "chapter5_ending_true_second", to: "chapter5_final_comment" },
  { from: "chapter5_ending_betrayed", to: "chapter5_final_comment" },
  { from: "chapter5_ending_ziying_inherit", to: "chapter5_final_comment" },
  { from: "chapter5_ending_clan_butcher", to: "chapter5_final_comment" },
  { from: "chapter5_ending_bashu", to: "chapter5_final_comment" },
  { from: "chapter5_ending_north_wolf", to: "chapter5_final_comment" },
  { from: "chapter5_ending_east_sea", to: "chapter5_final_comment" },
  { from: "chapter5_ending_rise_again", to: "chapter5_final_comment" },
];

export function getShortcutPathBySceneName(sceneName: unknown) {
  if (typeof sceneName !== "string") {
    return undefined;
  }

  return shortcutNodes.find((node) => node.sceneName === sceneName)?.path;
}
