export type ShortcutNode = {
  id: string;
  label: string;
  path: string;
  chapter: string;
  sceneName?: string;
  x: number;
  y: number;
};

export type ShortcutEdge = {
  from: string;
  to: string;
  label?: string;
};

export const shortcutNodes: ShortcutNode[] = [
  {
    id: "prologue_start",
    label: "沙丘之夜",
    path: "prologue_start",
    chapter: "序章",
    sceneName: "沙丘之夜",
    x: 8,
    y: 52,
  },
  {
    id: "prologue_at_door",
    label: "行宫夜门",
    path: "prologue_at_door",
    chapter: "序章",
    sceneName: "沙丘行宫·夜",
    x: 26,
    y: 52,
  },
  {
    id: "prologue_side_hall",
    label: "偏殿密谈",
    path: "prologue_side_hall",
    chapter: "序章",
    sceneName: "沙丘行宫·偏殿",
    x: 44,
    y: 52,
  },
  {
    id: "prologue_choice_a",
    label: "同意矫诏",
    path: "prologue_choice_a",
    chapter: "序章",
    sceneName: "沙丘之谋·同谋",
    x: 64,
    y: 16,
  },
  {
    id: "prologue_choice_b",
    label: "拒绝告发",
    path: "prologue_choice_b",
    chapter: "序章",
    sceneName: "沙丘之谋·决绝",
    x: 64,
    y: 52,
  },
  {
    id: "prologue_choice_c",
    label: "暗中布局",
    path: "prologue_choice_c",
    chapter: "序章",
    sceneName: "沙丘之谋·隐忍",
    x: 64,
    y: 88,
  },
  {
    id: "prologue_choice_b1",
    label: "告发 IF",
    path: "prologue_choice_b1",
    chapter: "序章",
    sceneName: "沙丘之谋·告发(IF)",
    x: 86,
    y: 14,
  },
  {
    id: "prologue_choice_b1_2",
    label: "告发失败",
    path: "prologue_choice_b1_2",
    chapter: "序章",
    sceneName: "沙丘之谋·告发失败",
    x: 86,
    y: 44,
  },
  {
    id: "prologue_choice_b2",
    label: "保持沉默",
    path: "prologue_choice_b2",
    chapter: "序章",
    sceneName: "沙丘之谋·沉默",
    x: 86,
    y: 74,
  },
  {
    id: "prologue_edict_strategy",
    label: "矫诏定策",
    path: "prologue_edict_strategy",
    chapter: "序章",
    sceneName: "沙丘行宫·矫诏定策",
    x: 108,
    y: 52,
  },
  {
    id: "prologue_edict_death",
    label: "赐死扶苏",
    path: "prologue_edict_death",
    chapter: "序章",
    sceneName: "矫诏定策·赐死",
    x: 130,
    y: 30,
  },
  {
    id: "prologue_edict_exile",
    label: "流放扶苏",
    path: "prologue_edict_exile",
    chapter: "序章",
    sceneName: "矫诏定策·流放",
    x: 130,
    y: 52,
  },
  {
    id: "prologue_edict_delay",
    label: "拖延待变",
    path: "prologue_edict_delay",
    chapter: "序章",
    sceneName: "矫诏定策·拖延",
    x: 130,
    y: 88,
  },
  {
    id: "prologue_secret_room",
    label: "密室内",
    path: "prologue_secret_room",
    chapter: "序章",
    sceneName: "沙丘行宫·密室内",
    x: 152,
    y: 52,
  },
  {
    id: "prologue_departure",
    label: "沙丘启程",
    path: "prologue_departure",
    chapter: "序章",
    sceneName: "沙丘行宫·出发",
    x: 172,
    y: 52,
  },
  {
    id: "prologue_end",
    label: "序章终",
    path: "prologue_end",
    chapter: "序章",
    sceneName: "序章·终",
    x: 192,
    y: 52,
  },
  {
    id: "prologue_b1_morning",
    label: "扶苏线晨光",
    path: "prologue_b1_morning",
    chapter: "序章",
    sceneName: "沙丘行宫·晨",
    x: 108,
    y: 7,
  },
  {
    id: "prologue_if_end",
    label: "IF 线暂止",
    path: "prologue_if_end",
    chapter: "序章",
    sceneName: "序章·终·扶苏即位线",
    x: 130,
    y: 7,
  },
  {
    id: "chapter1_start",
    label: "咸阳灵堂",
    path: "chapter1_start",
    chapter: "第一章",
    sceneName: "咸阳宫·灵堂",
    x: 214,
    y: 52,
  },
  {
    id: "chapter1_side_hall",
    label: "即位偏殿",
    path: "chapter1_side_hall",
    chapter: "第一章",
    sceneName: "咸阳宫·偏殿",
    x: 234,
    y: 52,
  },
  {
    id: "chapter1_fusu_dead",
    label: "扶苏已死",
    path: "chapter1_fusu_dead",
    chapter: "第一章",
    sceneName: "扶苏已死",
    x: 254,
    y: 24,
  },
  {
    id: "chapter1_fusu_exiled",
    label: "扶苏流放",
    path: "chapter1_fusu_exiled",
    chapter: "第一章",
    sceneName: "扶苏流放",
    x: 254,
    y: 52,
  },
  {
    id: "chapter1_fusu_delayed",
    label: "扶苏返京",
    path: "chapter1_fusu_delayed",
    chapter: "第一章",
    sceneName: "扶苏返京",
    x: 254,
    y: 80,
  },
  {
    id: "chapter1_fusu_common_end",
    label: "蒙氏阴影",
    path: "chapter1_fusu_common_end",
    chapter: "第一章",
    sceneName: "蒙氏阴影",
    x: 276,
    y: 52,
  },
  {
    id: "meng_decision",
    label: "章台廷议",
    path: "meng_decision",
    chapter: "第一章",
    sceneName: "咸阳宫·章台殿",
    x: 298,
    y: 52,
  },
  {
    id: "chapter1_meng_execute",
    label: "处死蒙氏",
    path: "chapter1_meng_execute",
    chapter: "第一章",
    sceneName: "蒙氏处死",
    x: 320,
    y: 24,
  },
  {
    id: "chapter1_meng_retain",
    label: "赦免留用",
    path: "chapter1_meng_retain",
    chapter: "第一章",
    sceneName: "蒙氏留用",
    x: 320,
    y: 52,
  },
  {
    id: "chapter1_meng_dismiss",
    label: "贬为庶民",
    path: "chapter1_meng_dismiss",
    chapter: "第一章",
    sceneName: "蒙氏免官",
    x: 320,
    y: 80,
  },
  {
    id: "chapter1_night_study",
    label: "寝殿奏章",
    path: "chapter1_night_study",
    chapter: "第一章",
    sceneName: "咸阳宫·寝殿",
    x: 342,
    y: 52,
  },
  {
    id: "chapter1_secret_record",
    label: "秘密记录",
    path: "chapter1_secret_record",
    chapter: "第一章",
    sceneName: "隐藏场景·秘密记录",
    x: 364,
    y: 28,
  },
  {
    id: "chapter1_clan_list",
    label: "宗室名单",
    path: "chapter1_clan_list",
    chapter: "第一章",
    sceneName: "咸阳宫·偏殿",
    x: 364,
    y: 72,
  },
  {
    id: "chapter1_ziying_meet",
    label: "子婴密会",
    path: "chapter1_ziying_meet",
    chapter: "第一章",
    sceneName: "隐藏场景·子婴密会",
    x: 386,
    y: 56,
  },
  {
    id: "chapter1_result",
    label: "第一章终",
    path: "chapter1_result",
    chapter: "第一章",
    sceneName: "第一章·终",
    x: 408,
    y: 82,
  },
  {
    id: "chapter2_start",
    label: "前情回顾",
    path: "chapter2_start",
    chapter: "第二章",
    sceneName: "第二章·前情",
    x: 430,
    y: 52,
  },
  {
    id: "chapter2_bedchamber",
    label: "宗室名单",
    path: "chapter2_bedchamber",
    chapter: "第二章",
    sceneName: "咸阳宫·寝殿",
    x: 452,
    y: 52,
  },
  {
    id: "chapter2_clan_debate",
    label: "偏殿廷议",
    path: "chapter2_clan_debate",
    chapter: "第二章",
    sceneName: "咸阳宫·偏殿",
    x: 474,
    y: 52,
  },
  {
    id: "chapter2_clan_massacre",
    label: "大开杀戒",
    path: "chapter2_clan_massacre",
    chapter: "第二章",
    sceneName: "宗室屠戮·大开杀戒",
    x: 498,
    y: 20,
  },
  {
    id: "chapter2_clan_limited",
    label: "只杀威胁者",
    path: "chapter2_clan_limited",
    chapter: "第二章",
    sceneName: "宗室屠戮·只杀威胁者",
    x: 498,
    y: 52,
  },
  {
    id: "chapter2_clan_protect",
    label: "庇护宗室",
    path: "chapter2_clan_protect",
    chapter: "第二章",
    sceneName: "宗室屠戮·庇护宗室",
    x: 498,
    y: 84,
  },
  {
    id: "chapter2_assassin",
    label: "刺客夜",
    path: "chapter2_assassin",
    chapter: "第二章",
    sceneName: "咸阳宫·刺客夜",
    x: 522,
    y: 52,
  },
  {
    id: "chapter2_guard_spies",
    label: "禁卫眼线",
    path: "chapter2_guard_spies",
    chapter: "第二章",
    sceneName: "隐藏场景·禁卫眼线",
    x: 544,
    y: 26,
  },
  {
    id: "chapter2_projects",
    label: "土木廷议",
    path: "chapter2_projects",
    chapter: "第二章",
    sceneName: "咸阳宫·章台殿",
    x: 566,
    y: 52,
  },
  {
    id: "chapter2_project_continue",
    label: "继续工程",
    path: "chapter2_project_continue",
    chapter: "第二章",
    sceneName: "大兴土木·继续工程",
    x: 590,
    y: 20,
  },
  {
    id: "chapter2_project_relief",
    label: "暂缓休养",
    path: "chapter2_project_relief",
    chapter: "第二章",
    sceneName: "大兴土木·暂缓休养",
    x: 590,
    y: 52,
  },
  {
    id: "chapter2_project_tax",
    label: "改革税制",
    path: "chapter2_project_tax",
    chapter: "第二章",
    sceneName: "大兴土木·改革税制",
    x: 590,
    y: 84,
  },
  {
    id: "chapter2_ziying_garden",
    label: "子婴菜园",
    path: "chapter2_ziying_garden",
    chapter: "第二章",
    sceneName: "公子婴的菜园",
    x: 614,
    y: 52,
  },
  {
    id: "chapter2_secret_room",
    label: "密室续录",
    path: "chapter2_secret_room",
    chapter: "第二章",
    sceneName: "咸阳宫·密室",
    x: 638,
    y: 28,
  },
  {
    id: "chapter2_result",
    label: "第二章终",
    path: "chapter2_result",
    chapter: "第二章",
    sceneName: "第二章·终",
    x: 660,
    y: 52,
  },
  {
    id: "chapter3_start",
    label: "前情回顾",
    path: "chapter3_start",
    chapter: "第三章",
    sceneName: "第三章·前情",
    x: 682,
    y: 52,
  },
  {
    id: "chapter3_dazexiang",
    label: "大泽乡",
    path: "chapter3_dazexiang",
    chapter: "第三章",
    sceneName: "大泽乡",
    x: 704,
    y: 52,
  },
  {
    id: "chapter3_rebellion_report",
    label: "起义军报",
    path: "chapter3_rebellion_report",
    chapter: "第三章",
    sceneName: "咸阳宫·章台殿·起义军报",
    x: 726,
    y: 52,
  },
  {
    id: "chapter3_suppress",
    label: "全力镇压",
    path: "chapter3_suppress",
    chapter: "第三章",
    sceneName: "应对起义·全力镇压",
    x: 750,
    y: 20,
  },
  {
    id: "chapter3_appease",
    label: "安抚招安",
    path: "chapter3_appease",
    chapter: "第三章",
    sceneName: "应对起义·安抚招安",
    x: 750,
    y: 52,
  },
  {
    id: "chapter3_ignore",
    label: "置之不理",
    path: "chapter3_ignore",
    chapter: "第三章",
    sceneName: "应对起义·坐视叛乱",
    x: 750,
    y: 84,
  },
  {
    id: "chapter3_li_si_conflict",
    label: "李赵决裂",
    path: "chapter3_li_si_conflict",
    chapter: "第三章",
    sceneName: "咸阳宫·偏殿·李赵决裂",
    x: 774,
    y: 52,
  },
  {
    id: "chapter3_execute_li_si",
    label: "诛杀李斯",
    path: "chapter3_execute_li_si",
    chapter: "第三章",
    sceneName: "李斯之死·处死李斯",
    x: 798,
    y: 20,
  },
  {
    id: "chapter3_protect_li_si",
    label: "保李斯",
    path: "chapter3_protect_li_si",
    chapter: "第三章",
    sceneName: "李斯之死·保李斯",
    x: 798,
    y: 52,
  },
  {
    id: "chapter3_kill_zhao_gao",
    label: "反杀赵高",
    path: "chapter3_kill_zhao_gao",
    chapter: "第三章",
    sceneName: "李斯之死·反杀赵高",
    x: 798,
    y: 84,
  },
  {
    id: "chapter3_zhang_han_report_alive",
    label: "章邯战报",
    path: "chapter3_zhang_han_report_alive",
    chapter: "第三章",
    sceneName: "章邯的战报·赵高存活",
    x: 824,
    y: 36,
  },
  {
    id: "chapter3_zhang_han_report_dead",
    label: "章邯战报",
    path: "chapter3_zhang_han_report_dead",
    chapter: "第三章",
    sceneName: "章邯的战报·赵高已死",
    x: 824,
    y: 112,
  },
  {
    id: "chapter3_reinforce_alive",
    label: "求援决策",
    path: "chapter3_reinforce_alive",
    chapter: "第三章",
    sceneName: "章邯求援·赵高存活",
    x: 850,
    y: 36,
  },
  {
    id: "chapter3_reinforce_dead",
    label: "求援决策",
    path: "chapter3_reinforce_dead",
    chapter: "第三章",
    sceneName: "章邯求援·赵高已死",
    x: 850,
    y: 112,
  },
  {
    id: "chapter3_support_zhang_alive",
    label: "全力增援",
    path: "chapter3_support_zhang_alive",
    chapter: "第三章",
    sceneName: "章邯求援·全力增援",
    x: 876,
    y: 12,
  },
  {
    id: "chapter3_suspect_zhang_alive",
    label: "拒绝增援",
    path: "chapter3_suspect_zhang_alive",
    chapter: "第三章",
    sceneName: "章邯求援·拒绝增援",
    x: 876,
    y: 42,
  },
  {
    id: "chapter3_send_zhao_front",
    label: "调虎离山",
    path: "chapter3_send_zhao_front",
    chapter: "第三章",
    sceneName: "章邯求援·调虎离山",
    x: 876,
    y: 72,
  },
  {
    id: "chapter3_support_zhang_dead",
    label: "全力增援",
    path: "chapter3_support_zhang_dead",
    chapter: "第三章",
    sceneName: "章邯求援·全力增援·赵高已死",
    x: 876,
    y: 100,
  },
  {
    id: "chapter3_suspect_zhang_dead",
    label: "拒绝增援",
    path: "chapter3_suspect_zhang_dead",
    chapter: "第三章",
    sceneName: "章邯求援·拒绝增援·赵高已死",
    x: 876,
    y: 130,
  },
  {
    id: "chapter3_eat_zhao_party",
    label: "蚕食赵党",
    path: "chapter3_eat_zhao_party",
    chapter: "第三章",
    sceneName: "隐藏场景·蚕食赵党",
    x: 902,
    y: 72,
  },
  {
    id: "chapter3_ziying_garden_alive",
    label: "菜园论政",
    path: "chapter3_ziying_garden_alive",
    chapter: "第三章",
    sceneName: "公子婴菜园·赵高存活",
    x: 928,
    y: 48,
  },
  {
    id: "chapter3_ziying_garden_dead",
    label: "菜园论政",
    path: "chapter3_ziying_garden_dead",
    chapter: "第三章",
    sceneName: "公子婴菜园·赵高已死",
    x: 928,
    y: 116,
  },
  {
    id: "chapter3_result_alive",
    label: "第三章终",
    path: "chapter3_result_alive",
    chapter: "第三章",
    sceneName: "第三章·终·赵高存活",
    x: 954,
    y: 48,
  },
  {
    id: "chapter3_result_dead",
    label: "第三章终",
    path: "chapter3_result_dead",
    chapter: "第三章",
    sceneName: "第三章·终·赵高已死",
    x: 954,
    y: 116,
  },
  {
    id: "chapter4_start",
    label: "前情回顾",
    path: "chapter4_start",
    chapter: "第四章",
    sceneName: "第四章·前情",
    x: 982,
    y: 82,
  },
  {
    id: "chapter4_deer_court",
    label: "指鹿为马",
    path: "chapter4_deer_court",
    chapter: "第四章",
    sceneName: "咸阳宫·章台殿·指鹿为马",
    x: 1008,
    y: 36,
  },
  {
    id: "chapter4_deer_is_deer",
    label: "指鹿为鹿",
    path: "chapter4_deer_is_deer",
    chapter: "第四章",
    sceneName: "指鹿为马·指鹿为鹿",
    x: 1034,
    y: 12,
  },
  {
    id: "chapter4_deer_is_horse",
    label: "违心称马",
    path: "chapter4_deer_is_horse",
    chapter: "第四章",
    sceneName: "指鹿为马·违心称马",
    x: 1034,
    y: 36,
  },
  {
    id: "chapter4_countermove",
    label: "反将一军",
    path: "chapter4_countermove",
    chapter: "第四章",
    sceneName: "指鹿为马·反将一军",
    x: 1034,
    y: 60,
  },
  {
    id: "chapter4_breakout_plan",
    label: "破局三策",
    path: "chapter4_breakout_plan",
    chapter: "第四章",
    sceneName: "咸阳宫·寝殿·破局三策",
    x: 1062,
    y: 36,
  },
  {
    id: "chapter4_call_zhang_han",
    label: "密诏章邯",
    path: "chapter4_call_zhang_han",
    chapter: "第四章",
    sceneName: "破局三策·密诏章邯",
    x: 1090,
    y: 12,
  },
  {
    id: "chapter4_leave_xianyang",
    label: "离京出巡",
    path: "chapter4_leave_xianyang",
    chapter: "第四章",
    sceneName: "破局三策·离京出巡",
    x: 1090,
    y: 36,
  },
  {
    id: "chapter4_palace_assassination",
    label: "宫中刺杀",
    path: "chapter4_palace_assassination",
    chapter: "第四章",
    sceneName: "破局三策·宫中刺杀",
    x: 1090,
    y: 60,
  },
  {
    id: "chapter4_julu_report_alive",
    label: "巨鹿战报",
    path: "chapter4_julu_report_alive",
    chapter: "第四章",
    sceneName: "巨鹿战报·赵高存活",
    x: 1118,
    y: 36,
  },
  {
    id: "chapter4_regency_court",
    label: "亲政朝会",
    path: "chapter4_regency_court",
    chapter: "第四章",
    sceneName: "亲政之路·章台殿",
    x: 1118,
    y: 106,
  },
  {
    id: "chapter4_li_si_policy",
    label: "李斯削藩",
    path: "chapter4_li_si_policy",
    chapter: "第四章",
    sceneName: "亲政之路·李斯削藩策",
    x: 1146,
    y: 106,
  },
  {
    id: "chapter4_reform_garden",
    label: "改法之议",
    path: "chapter4_reform_garden",
    chapter: "第四章",
    sceneName: "亲政之路·改法之议",
    x: 1174,
    y: 106,
  },
  {
    id: "chapter4_centralize",
    label: "削藩集权",
    path: "chapter4_centralize",
    chapter: "第四章",
    sceneName: "治国之路·削藩集权",
    x: 1202,
    y: 86,
  },
  {
    id: "chapter4_tui_en",
    label: "推恩分封",
    path: "chapter4_tui_en",
    chapter: "第四章",
    sceneName: "治国之路·推恩分封",
    x: 1202,
    y: 110,
  },
  {
    id: "chapter4_reform_law",
    label: "改秦法",
    path: "chapter4_reform_law",
    chapter: "第四章",
    sceneName: "治国之路·改秦法",
    x: 1202,
    y: 134,
  },
  {
    id: "chapter4_julu_report_dead",
    label: "巨鹿求援",
    path: "chapter4_julu_report_dead",
    chapter: "第四章",
    sceneName: "巨鹿之援·赵高已死",
    x: 1230,
    y: 110,
  },
  {
    id: "chapter4_personal_campaign",
    label: "亲征",
    path: "chapter4_personal_campaign",
    chapter: "第四章",
    sceneName: "巨鹿之援·亲征",
    x: 1258,
    y: 70,
  },
  {
    id: "chapter4_send_zhao_supervise",
    label: "赵高监军",
    path: "chapter4_send_zhao_supervise",
    chapter: "第四章",
    sceneName: "巨鹿之援·赵高监军",
    x: 1146,
    y: 94,
  },
  {
    id: "chapter4_reinforce_only",
    label: "增援不亲征",
    path: "chapter4_reinforce_only",
    chapter: "第四章",
    sceneName: "巨鹿之援·增援不亲征",
    x: 1258,
    y: 118,
  },
  {
    id: "chapter4_abandon_zhang",
    label: "坐视章邯",
    path: "chapter4_abandon_zhang",
    chapter: "第四章",
    sceneName: "巨鹿之援·坐视章邯",
    x: 1258,
    y: 142,
  },
  {
    id: "chapter4_result",
    label: "第四章终",
    path: "chapter4_result",
    chapter: "第四章",
    sceneName: "第四章·终",
    x: 1286,
    y: 106,
  },
  {
    id: "chapter5_start",
    label: "第五章前情",
    path: "chapter5_start",
    chapter: "第五章",
    sceneName: "第五章·前情",
    x: 1314,
    y: 106,
  },
  {
    id: "chapter5_mingjun_camp",
    label: "函谷军帐",
    path: "chapter5_mingjun_camp",
    chapter: "第五章",
    sceneName: "函谷关外·大军营帐",
    x: 1342,
    y: 48,
  },
  {
    id: "chapter5_julu_encircle",
    label: "围而不战",
    path: "chapter5_julu_encircle",
    chapter: "第五章",
    sceneName: "巨鹿决战·围而不战",
    x: 1370,
    y: 24,
  },
  {
    id: "chapter5_julu_charge",
    label: "主动出击",
    path: "chapter5_julu_charge",
    chapter: "第五章",
    sceneName: "巨鹿决战·主动出击",
    x: 1370,
    y: 72,
  },
  {
    id: "chapter5_mingjun_ending_choice",
    label: "明君结局分支",
    path: "chapter5_mingjun_ending_choice",
    chapter: "第五章",
    sceneName: "明君线·结局分支",
    x: 1398,
    y: 48,
  },
  {
    id: "chapter5_ending_mingjun",
    label: "明君逆袭",
    path: "chapter5_ending_mingjun",
    chapter: "第五章",
    sceneName: "结局·明君逆袭",
    x: 1426,
    y: 4,
  },
  {
    id: "chapter5_ending_rebuild",
    label: "重塑天下",
    path: "chapter5_ending_rebuild",
    chapter: "第五章",
    sceneName: "结局·重塑天下",
    x: 1426,
    y: 30,
  },
  {
    id: "chapter5_ending_hidden_dragon",
    label: "隐龙出渊",
    path: "chapter5_ending_hidden_dragon",
    chapter: "第五章",
    sceneName: "结局·隐龙出渊",
    x: 1426,
    y: 56,
  },
  {
    id: "chapter5_ending_redemption",
    label: "英雄救赎",
    path: "chapter5_ending_redemption",
    chapter: "第五章",
    sceneName: "结局·英雄救赎",
    x: 1426,
    y: 82,
  },
  {
    id: "chapter5_ending_zhang_surrender",
    label: "章邯之降",
    path: "chapter5_ending_zhang_surrender",
    chapter: "第五章",
    sceneName: "结局·章邯之降",
    x: 1426,
    y: 108,
  },
  {
    id: "chapter5_puppet_court",
    label: "清洗赵党",
    path: "chapter5_puppet_court",
    chapter: "第五章",
    sceneName: "咸阳宫·章台殿·清洗赵党",
    x: 1342,
    y: 126,
  },
  {
    id: "chapter5_purge_hard",
    label: "雷霆清洗",
    path: "chapter5_purge_hard",
    chapter: "第五章",
    sceneName: "清洗赵党·雷霆手段",
    x: 1370,
    y: 116,
  },
  {
    id: "chapter5_purge_soft",
    label: "分化瓦解",
    path: "chapter5_purge_soft",
    chapter: "第五章",
    sceneName: "清洗赵党·分化瓦解",
    x: 1370,
    y: 144,
  },
  {
    id: "chapter5_puppet_ending_choice",
    label: "翻身结局分支",
    path: "chapter5_puppet_ending_choice",
    chapter: "第五章",
    sceneName: "傀儡翻身线·结局分支",
    x: 1398,
    y: 130,
  },
  {
    id: "chapter5_ending_puppet",
    label: "傀儡翻身",
    path: "chapter5_ending_puppet",
    chapter: "第五章",
    sceneName: "结局·傀儡翻身",
    x: 1426,
    y: 132,
  },
  {
    id: "chapter5_ending_borrow_blade",
    label: "借刀杀人",
    path: "chapter5_ending_borrow_blade",
    chapter: "第五章",
    sceneName: "结局·借刀杀人",
    x: 1426,
    y: 158,
  },
  {
    id: "chapter5_fall_wangyi",
    label: "望夷终局",
    path: "chapter5_fall_wangyi",
    chapter: "第五章",
    sceneName: "望夷宫·雪夜",
    x: 1342,
    y: 170,
  },
  {
    id: "chapter5_ending_true_second",
    label: "真实二世",
    path: "chapter5_ending_true_second",
    chapter: "第五章",
    sceneName: "结局·真实的二世",
    x: 1370,
    y: 166,
  },
  {
    id: "chapter5_ending_betrayed",
    label: "众叛亲离",
    path: "chapter5_ending_betrayed",
    chapter: "第五章",
    sceneName: "结局·众叛亲离",
    x: 1398,
    y: 180,
  },
  {
    id: "chapter5_ending_ziying_inherit",
    label: "子婴继承",
    path: "chapter5_ending_ziying_inherit",
    chapter: "第五章",
    sceneName: "结局·子婴的继承",
    x: 1426,
    y: 178,
  },
  {
    id: "chapter5_ending_clan_butcher",
    label: "宗室屠夫终局",
    path: "chapter5_ending_clan_butcher",
    chapter: "第五章",
    sceneName: "结局·宗室屠夫",
    x: 1426,
    y: 200,
  },
  {
    id: "chapter5_exile_snow",
    label: "逃亡雪地",
    path: "chapter5_exile_snow",
    chapter: "第五章",
    sceneName: "咸阳郊外·雪地",
    x: 1342,
    y: 208,
  },
  {
    id: "chapter5_ending_bashu",
    label: "巴蜀之主",
    path: "chapter5_ending_bashu",
    chapter: "第五章",
    sceneName: "结局·巴蜀之主",
    x: 1370,
    y: 208,
  },
  {
    id: "chapter5_ending_north_wolf",
    label: "北方之狼",
    path: "chapter5_ending_north_wolf",
    chapter: "第五章",
    sceneName: "结局·北方之狼",
    x: 1398,
    y: 208,
  },
  {
    id: "chapter5_ending_east_sea",
    label: "东渡沧海",
    path: "chapter5_ending_east_sea",
    chapter: "第五章",
    sceneName: "结局·东渡沧海",
    x: 1426,
    y: 220,
  },
  {
    id: "chapter5_ending_rise_again",
    label: "东山再起",
    path: "chapter5_ending_rise_again",
    chapter: "第五章",
    sceneName: "结局·东山再起",
    x: 1426,
    y: 244,
  },
  {
    id: "chapter5_brother_cell",
    label: "兄弟相残",
    path: "chapter5_brother_cell",
    chapter: "第五章",
    sceneName: "扶苏线·章台囚室",
    x: 1342,
    y: 16,
  },
  {
    id: "chapter5_final_comment",
    label: "终章史评",
    path: "chapter5_final_comment",
    chapter: "第五章",
    sceneName: "终章·史家评语",
    x: 1480,
    y: 106,
  },
];

export const shortcutEdges: ShortcutEdge[] = [
  { from: "prologue_start", to: "prologue_at_door" },
  { from: "prologue_at_door", to: "prologue_side_hall" },
  { from: "prologue_side_hall", to: "prologue_choice_a", label: "A" },
  { from: "prologue_side_hall", to: "prologue_choice_b", label: "B" },
  { from: "prologue_side_hall", to: "prologue_choice_c", label: "C" },
  { from: "prologue_choice_b", to: "prologue_choice_b1", label: "B1" },
  { from: "prologue_choice_b", to: "prologue_choice_b1_2", label: "B1-2" },
  { from: "prologue_choice_b", to: "prologue_choice_b2", label: "B2" },
  { from: "prologue_choice_a", to: "prologue_edict_strategy" },
  { from: "prologue_choice_b1", to: "prologue_b1_morning" },
  { from: "prologue_choice_b1_2", to: "prologue_edict_strategy" },
  { from: "prologue_choice_b2", to: "prologue_edict_strategy" },
  { from: "prologue_choice_c", to: "prologue_edict_strategy" },
  { from: "prologue_edict_strategy", to: "prologue_edict_death", label: "一" },
  { from: "prologue_edict_strategy", to: "prologue_edict_exile", label: "二" },
  { from: "prologue_edict_strategy", to: "prologue_edict_delay", label: "三" },
  { from: "prologue_edict_death", to: "prologue_secret_room" },
  { from: "prologue_edict_exile", to: "prologue_secret_room" },
  { from: "prologue_edict_delay", to: "prologue_secret_room" },
  { from: "prologue_secret_room", to: "prologue_departure" },
  { from: "prologue_departure", to: "prologue_end" },
  { from: "prologue_b1_morning", to: "prologue_if_end" },
  { from: "prologue_end", to: "chapter1_start" },
  { from: "chapter1_start", to: "chapter1_side_hall" },
  { from: "chapter1_side_hall", to: "chapter1_fusu_dead", label: "死" },
  { from: "chapter1_side_hall", to: "chapter1_fusu_exiled", label: "流" },
  { from: "chapter1_side_hall", to: "chapter1_fusu_delayed", label: "返" },
  { from: "chapter1_fusu_dead", to: "chapter1_fusu_common_end" },
  { from: "chapter1_fusu_exiled", to: "chapter1_fusu_common_end" },
  { from: "chapter1_fusu_delayed", to: "chapter1_fusu_common_end" },
  { from: "chapter1_fusu_common_end", to: "meng_decision" },
  { from: "meng_decision", to: "chapter1_meng_execute", label: "A" },
  { from: "meng_decision", to: "chapter1_meng_retain", label: "B" },
  { from: "meng_decision", to: "chapter1_meng_dismiss", label: "C" },
  { from: "chapter1_meng_execute", to: "chapter1_night_study" },
  { from: "chapter1_meng_retain", to: "chapter1_night_study" },
  { from: "chapter1_meng_dismiss", to: "chapter1_night_study" },
  { from: "chapter1_night_study", to: "chapter1_secret_record", label: "隐" },
  { from: "chapter1_night_study", to: "chapter1_clan_list" },
  { from: "chapter1_secret_record", to: "chapter1_clan_list" },
  { from: "chapter1_clan_list", to: "chapter1_ziying_meet", label: "隐" },
  { from: "chapter1_clan_list", to: "chapter1_result", label: "主" },
  { from: "chapter1_ziying_meet", to: "chapter1_result" },
  { from: "chapter1_result", to: "chapter2_start" },
  { from: "chapter2_start", to: "chapter2_bedchamber" },
  { from: "chapter2_bedchamber", to: "chapter2_clan_debate" },
  { from: "chapter2_clan_debate", to: "chapter2_clan_massacre", label: "A" },
  { from: "chapter2_clan_debate", to: "chapter2_clan_limited", label: "B" },
  { from: "chapter2_clan_debate", to: "chapter2_clan_protect", label: "C" },
  { from: "chapter2_clan_massacre", to: "chapter2_assassin" },
  { from: "chapter2_clan_limited", to: "chapter2_assassin" },
  { from: "chapter2_clan_protect", to: "chapter2_assassin" },
  { from: "chapter2_assassin", to: "chapter2_guard_spies", label: "隐" },
  { from: "chapter2_assassin", to: "chapter2_projects", label: "主" },
  { from: "chapter2_guard_spies", to: "chapter2_projects" },
  { from: "chapter2_projects", to: "chapter2_project_continue", label: "A" },
  { from: "chapter2_projects", to: "chapter2_project_relief", label: "B" },
  { from: "chapter2_projects", to: "chapter2_project_tax", label: "C" },
  { from: "chapter2_project_continue", to: "chapter2_ziying_garden" },
  { from: "chapter2_project_relief", to: "chapter2_ziying_garden" },
  { from: "chapter2_project_tax", to: "chapter2_ziying_garden" },
  { from: "chapter2_ziying_garden", to: "chapter2_secret_room", label: "隐" },
  { from: "chapter2_ziying_garden", to: "chapter2_result", label: "主" },
  { from: "chapter2_secret_room", to: "chapter2_result" },
  { from: "chapter2_result", to: "chapter3_start" },
  { from: "chapter3_start", to: "chapter3_dazexiang" },
  { from: "chapter3_dazexiang", to: "chapter3_rebellion_report" },
  { from: "chapter3_rebellion_report", to: "chapter3_suppress", label: "A" },
  { from: "chapter3_rebellion_report", to: "chapter3_appease", label: "B" },
  { from: "chapter3_rebellion_report", to: "chapter3_ignore", label: "C" },
  { from: "chapter3_suppress", to: "chapter3_li_si_conflict" },
  { from: "chapter3_appease", to: "chapter3_li_si_conflict" },
  { from: "chapter3_ignore", to: "chapter3_li_si_conflict" },
  { from: "chapter3_li_si_conflict", to: "chapter3_execute_li_si", label: "A" },
  { from: "chapter3_li_si_conflict", to: "chapter3_protect_li_si", label: "B" },
  { from: "chapter3_li_si_conflict", to: "chapter3_kill_zhao_gao", label: "隐" },
  { from: "chapter3_execute_li_si", to: "chapter3_zhang_han_report_alive" },
  { from: "chapter3_protect_li_si", to: "chapter3_zhang_han_report_alive" },
  { from: "chapter3_kill_zhao_gao", to: "chapter3_zhang_han_report_dead" },
  { from: "chapter3_zhang_han_report_alive", to: "chapter3_reinforce_alive" },
  { from: "chapter3_zhang_han_report_dead", to: "chapter3_reinforce_dead" },
  { from: "chapter3_reinforce_alive", to: "chapter3_support_zhang_alive", label: "A" },
  { from: "chapter3_reinforce_alive", to: "chapter3_suspect_zhang_alive", label: "B" },
  { from: "chapter3_reinforce_alive", to: "chapter3_send_zhao_front", label: "C" },
  { from: "chapter3_reinforce_dead", to: "chapter3_support_zhang_dead", label: "A" },
  { from: "chapter3_reinforce_dead", to: "chapter3_suspect_zhang_dead", label: "B" },
  { from: "chapter3_support_zhang_alive", to: "chapter3_ziying_garden_alive" },
  { from: "chapter3_suspect_zhang_alive", to: "chapter3_ziying_garden_alive" },
  { from: "chapter3_send_zhao_front", to: "chapter3_eat_zhao_party", label: "隐" },
  { from: "chapter3_send_zhao_front", to: "chapter3_ziying_garden_alive", label: "主" },
  { from: "chapter3_eat_zhao_party", to: "chapter3_ziying_garden_alive" },
  { from: "chapter3_ziying_garden_alive", to: "chapter3_result_alive" },
  { from: "chapter3_support_zhang_dead", to: "chapter3_ziying_garden_dead" },
  { from: "chapter3_suspect_zhang_dead", to: "chapter3_ziying_garden_dead" },
  { from: "chapter3_ziying_garden_dead", to: "chapter3_result_dead" },
  { from: "chapter3_result_alive", to: "chapter4_start" },
  { from: "chapter3_result_dead", to: "chapter4_start" },
  { from: "chapter4_start", to: "chapter4_deer_court", label: "赵存" },
  { from: "chapter4_start", to: "chapter4_regency_court", label: "赵亡" },
  { from: "chapter4_deer_court", to: "chapter4_deer_is_deer", label: "A" },
  { from: "chapter4_deer_court", to: "chapter4_deer_is_horse", label: "B" },
  { from: "chapter4_deer_court", to: "chapter4_countermove", label: "隐" },
  { from: "chapter4_deer_is_deer", to: "chapter4_breakout_plan" },
  { from: "chapter4_deer_is_horse", to: "chapter4_breakout_plan" },
  { from: "chapter4_countermove", to: "chapter4_breakout_plan" },
  { from: "chapter4_breakout_plan", to: "chapter4_call_zhang_han", label: "A" },
  { from: "chapter4_breakout_plan", to: "chapter4_leave_xianyang", label: "B" },
  { from: "chapter4_breakout_plan", to: "chapter4_palace_assassination", label: "C" },
  { from: "chapter4_call_zhang_han", to: "chapter4_julu_report_alive" },
  { from: "chapter4_leave_xianyang", to: "chapter4_julu_report_alive" },
  { from: "chapter4_palace_assassination", to: "chapter4_regency_court" },
  { from: "chapter4_julu_report_alive", to: "chapter4_personal_campaign", label: "A" },
  { from: "chapter4_julu_report_alive", to: "chapter4_send_zhao_supervise", label: "B" },
  { from: "chapter4_julu_report_alive", to: "chapter4_abandon_zhang", label: "C" },
  { from: "chapter4_regency_court", to: "chapter4_li_si_policy" },
  { from: "chapter4_li_si_policy", to: "chapter4_reform_garden" },
  { from: "chapter4_reform_garden", to: "chapter4_centralize", label: "A" },
  { from: "chapter4_reform_garden", to: "chapter4_tui_en", label: "B" },
  { from: "chapter4_reform_garden", to: "chapter4_reform_law", label: "C" },
  { from: "chapter4_centralize", to: "chapter4_julu_report_dead" },
  { from: "chapter4_tui_en", to: "chapter4_julu_report_dead" },
  { from: "chapter4_reform_law", to: "chapter4_julu_report_dead" },
  { from: "chapter4_julu_report_dead", to: "chapter4_personal_campaign", label: "A" },
  { from: "chapter4_julu_report_dead", to: "chapter4_reinforce_only", label: "B" },
  { from: "chapter4_julu_report_dead", to: "chapter4_abandon_zhang", label: "C" },
  { from: "chapter4_personal_campaign", to: "chapter4_result" },
  { from: "chapter4_send_zhao_supervise", to: "chapter4_result" },
  { from: "chapter4_reinforce_only", to: "chapter4_result" },
  { from: "chapter4_abandon_zhang", to: "chapter4_result" },
  { from: "chapter4_result", to: "chapter5_start" },
  { from: "chapter5_start", to: "chapter5_mingjun_camp", label: "亲/赵亡" },
  { from: "chapter5_start", to: "chapter5_puppet_court", label: "赵监" },
  { from: "chapter5_start", to: "chapter5_fall_wangyi", label: "败" },
  { from: "chapter5_start", to: "chapter5_exile_snow", label: "逃" },
  { from: "chapter5_start", to: "chapter5_brother_cell", label: "IF" },
  { from: "chapter5_mingjun_camp", to: "chapter5_julu_encircle", label: "A" },
  { from: "chapter5_mingjun_camp", to: "chapter5_julu_charge", label: "B" },
  { from: "chapter5_julu_encircle", to: "chapter5_mingjun_ending_choice" },
  { from: "chapter5_julu_charge", to: "chapter5_mingjun_ending_choice" },
  { from: "chapter5_mingjun_ending_choice", to: "chapter5_ending_mingjun" },
  { from: "chapter5_mingjun_ending_choice", to: "chapter5_ending_rebuild" },
  { from: "chapter5_mingjun_ending_choice", to: "chapter5_ending_hidden_dragon", label: "隐" },
  { from: "chapter5_mingjun_ending_choice", to: "chapter5_ending_redemption", label: "救" },
  { from: "chapter5_mingjun_ending_choice", to: "chapter5_ending_zhang_surrender" },
  { from: "chapter5_puppet_court", to: "chapter5_purge_hard", label: "A" },
  { from: "chapter5_puppet_court", to: "chapter5_purge_soft", label: "B" },
  { from: "chapter5_purge_hard", to: "chapter5_puppet_ending_choice" },
  { from: "chapter5_purge_soft", to: "chapter5_puppet_ending_choice" },
  { from: "chapter5_puppet_ending_choice", to: "chapter5_ending_puppet" },
  { from: "chapter5_puppet_ending_choice", to: "chapter5_ending_borrow_blade", label: "隐" },
  { from: "chapter5_fall_wangyi", to: "chapter5_ending_true_second", label: "A" },
  { from: "chapter5_fall_wangyi", to: "chapter5_ending_betrayed", label: "B" },
  { from: "chapter5_fall_wangyi", to: "chapter5_ending_ziying_inherit", label: "C" },
  { from: "chapter5_fall_wangyi", to: "chapter5_ending_clan_butcher", label: "宗" },
  { from: "chapter5_exile_snow", to: "chapter5_ending_bashu", label: "A" },
  { from: "chapter5_exile_snow", to: "chapter5_ending_north_wolf", label: "B" },
  { from: "chapter5_exile_snow", to: "chapter5_ending_east_sea", label: "C" },
  { from: "chapter5_exile_snow", to: "chapter5_ending_rise_again", label: "隐" },
  { from: "chapter5_brother_cell", to: "chapter5_final_comment" },
  { from: "chapter5_ending_mingjun", to: "chapter5_final_comment" },
  { from: "chapter5_ending_rebuild", to: "chapter5_final_comment" },
  { from: "chapter5_ending_hidden_dragon", to: "chapter5_final_comment" },
  { from: "chapter5_ending_redemption", to: "chapter5_final_comment" },
  { from: "chapter5_ending_zhang_surrender", to: "chapter5_final_comment" },
  { from: "chapter5_ending_puppet", to: "chapter5_final_comment" },
  { from: "chapter5_ending_borrow_blade", to: "chapter5_final_comment" },
  { from: "chapter5_ending_true_second", to: "chapter5_final_comment" },
  { from: "chapter5_ending_betrayed", to: "chapter5_final_comment" },
  { from: "chapter5_ending_ziying_inherit", to: "chapter5_final_comment" },
  { from: "chapter5_ending_clan_butcher", to: "chapter5_final_comment" },
  { from: "chapter5_ending_bashu", to: "chapter5_final_comment" },
  { from: "chapter5_ending_north_wolf", to: "chapter5_final_comment" },
  { from: "chapter5_ending_east_sea", to: "chapter5_final_comment" },
  { from: "chapter5_ending_rise_again", to: "chapter5_final_comment" },
];

export function getShortcutPathBySceneName(sceneName: unknown) {
  if (typeof sceneName !== "string") {
    return undefined;
  }

  return shortcutNodes.find((node) => node.sceneName === sceneName)?.path;
}
